feat: accept third-party `Blob`s in `FormData`
nodejs/undici pull request #1099
Opened 2021-11-16 12:50 UTC by wojpawlik

Works around https://github.com/nodejs/node/issues/37340.
Advances https://github.com/telegraf/telegraf/issues/1502.
Closes #930.

2021-11-16 13:07 UTC, mcollina requested changes
Good work! Can you please add a unit test?

2021-11-16 13:07 UTC, mcollina commented on lib/fetch/util.js
> +  return (
Could you add an `instanceof Blob` as a fast path?

2021-11-16 14:59 UTC, ronag approved these changes

2021-11-17 07:58 UTC, mcollina approved these changes
lgtm

2021-11-17 07:58 UTC, merged