feat: implement `makePolicyContainer` and `clonePolicyContainer``
nodejs/undici pull request #1243
Opened 2022-02-19 05:34 UTC by suneettipirneni

Implements:
- https://html.spec.whatwg.org/multipage/origin.html#policy-container
- https://html.spec.whatwg.org/multipage/origin.html#clone-a-policy-container

2022-02-19 07:17 UTC, mcollina requested changes
What's the purpose of these? Isn't it better than we throw?

2022-02-19 10:06 UTC, ronag commented on lib/fetch/util.js
> +  }
This is missing spec comments

2022-02-19 14:13 UTC, suneettipirneni commented
> What's the purpose of these? Isn't it better than we throw?

Sorry, I'm unsure what you mean by this. Can you explain?

2022-02-19 18:02 UTC, ronag approved these changes

2022-02-22 10:58 UTC, mcollina commented
What is the purpose of those functions in the context of undici? We do not have a CSP in Node.js, so why are they here?
IMHO we should not have those functions or throw in them when called.

2022-03-14 23:27 UTC, closed without merging