fix: correct type for path option
nodejs/undici pull request #1282
Opened 2022-03-16 09:07 UTC by is2ei

Refs: #1011

`undici.request` accepts `path` option.
POC: https://github.com/is2ei/POC-nodejs-undici-1011
code: https://github.com/nodejs/undici/blob/d7eac3e4e57c387bfd954da7a28e84138c243d4c/index.js#L63-L75

2022-03-16 09:12 UTC, ronag commented on README.md
> +  * **path** `String` (optional)
`path` is already part of `RequestOptions`

2022-03-16 09:13 UTC, ronag requested changes
path is already part of these through extending parent structure

2022-03-16 09:26 UTC, is2ei commented
@ronag 
Thanks for your comment. I basically try to solve 2 problems related to #1011.

1. wrong type definition
2. document for `undici.request` lacks some information.

When using TypeScript, you can not pass the `path` option to `undici.request` because the type definition omits the `path` option. But when using JavaScript, you can pass the `path` option to `undici.request` and it works. So I fixed the type definition.

https://github.com/nodejs/undici/blob/d7eac3e4e57c387bfd954da7a28e84138c243d4c/index.js#L63-L68

Also, I found `method` option is documented even though `DispatchOptions` already has it. I guess the difference is `method` is mandatory in `DispatchOptions` but optional in `undici.request` option. `path` option has the same situation so I documented it.

https://github.com/nodejs/undici/blob/d7eac3e4e57c387bfd954da7a28e84138c243d4c/types/api.d.ts#L13-L17

2022-03-16 11:33 UTC, ronag commented
> When using TypeScript, you can not pass the path option to undici.request because the type definition omits the path option. But when using JavaScript, you can pass the path option to undici.request and it works. So I fixed the type definition.

I think the typescript version is correct and reflects intended/recommended usage.

2022-03-16 11:49 UTC, is2ei commented
@ronag 

> Maybe we should throw?

Ok. I'll try.

2022-03-16 13:08 UTC, is2ei commented
@ronag 
I changed the code. Could you review it?
I basically agree with your opinion,  but I'd be worried if it would be a breaking change.

2023-05-31 02:41 UTC, hebertcisco requested changes
I saw that your pull request has conflicts, have you tried to resolve these conflicts?

2023-05-31 02:41 UTC, hebertcisco requested changes
I saw that your pull request has conflicts, have you tried to resolve these conflicts?

2023-05-31 14:55 UTC, hebertcisco reviewed
@ronag What do you think of this pull request and the changes made to it? Would it be mergeable and adequate?

2023-05-31 14:59 UTC, is2ei commented
@hebertcisco 
I fixed the conflict, but it looks `path` option is actually used now.
Do we still need this change?

2023-06-10 06:04 UTC, mcollina commented
I think this can be closed, thanks!

2023-06-10 06:04 UTC, closed without merging