fetch: replace `Proxy` objects
nodejs/undici pull request #1299
Opened 2022-03-22 04:45 UTC by KhafraDev

Should alleviate most perf regressions in #1295, I still have no idea what a filtered response is and it's most likely wrong, but all of the tests pass.

2022-03-22 04:46 UTC, KhafraDev commented on lib/fetch/headers.js
> +  filter = () => true;
Needed `babel-eslint` for standard because it couldn't parse this properly. There's an issue on github with this solution I can pull up if you need.

2022-03-22 05:07 UTC, ronag commented on lib/fetch/headers.js
> +    this.push(...headersList) // copy values
You can’t copy.

2022-03-22 05:08 UTC, ronag requested changes
A filtered object is a view on the internal object. It’s not enough to have a copy.

2022-03-22 05:55 UTC, ronag commented
So what you need to do here is:

Implement a `FilteredResponse` that acts like an explicit proxy forwarding everything except what is filtered to the internalResponse.

Implement a `FiltereredHeadersList` which does the same as above. In order to do that we probably need to change so that `HeadersList` doesn't extend `Array` but instead has a array store property which you can share references to.

2022-03-22 14:26 UTC, KhafraDev commented
That makes sense and I definitely see why you chose proxies. Think I can work around it (already have a better `FilteredResponseView` ready.

2022-03-22 14:31 UTC, closed without merging

2022-05-26 03:29 UTC, KhafraDev commented
@ronag I've thought about this quite a bit and came up with a possibly acceptable solution (I know this is an old issue...);

I think `response` (the internal one, not to be confused with the fetch `Response`) is better suited as a class. In doing so, we can easily make a "response" filtered by, for example, setting `response.filtered = true`. Of course it would also need some method for property lookups and handle the filtering logic there. Same could be done for `HeadersList` without that much change, simply by adding a `.filtered` property and running a pre-set filtering function if it's filtered.

However, I don't think server-environments (deno, cf) even do this filtering in the first place and I don't see the benefit of keeping it in.