feat(fecth): corsCheck
nodejs/undici pull request #1315
Opened 2022-03-30 23:45 UTC by hemanth

CORS check.

2022-03-30 23:46 UTC, hemanth commented on lib/fetch/util.js
> +  // Should we do the isomorphic encoding?
Seeking some clarity on this.

2022-03-31 07:07 UTC, mcollina reviewed
Why are we adding this? We'd
never support cors.

2022-03-31 07:47 UTC, ronag commented
@benjamingr

2022-03-31 17:19 UTC, KhafraDev commented
If this PR isn't merged 83defac59ca50494e88b10ff22226b524f1f7dee should probably get reverted too as it deals with cross origin stuff as well

> Cross-origin read blocking, better known as CORB, is an algorithm which identifies dubious cross-origin resource fetches (e.g., fetches that would fail anyway like attempts to render JSON inside an img element) and blocks them before they reach a web page. CORB reduces the risk of leaking sensitive data by keeping it further from cross-origin web pages.

2022-03-31 17:21 UTC, benjamingr commented
@ronag I agree with Matteo on this

2022-03-31 17:28 UTC, ronag commented
We should replace the implementation parts with a clear comment that this stub is out of scope.

2022-03-31 19:24 UTC, hemanth commented
Ah, it makes more sense, was doubtful too. 

Should we revisit the other unimplemented methods?

2022-04-02 05:10 UTC, hemanth commented
We have the following to be implemented:

1. crossOriginResourcePolicyCheck
2. TAOCheck
3. coarsenedSharedCurrentTime
4. makePolicyContainer
5. clonePolicyContainer
6. determineRequestsReferrer
7. tryUpgradeRequestToAPotentiallyTrustworthyURL

2022-07-01 07:22 UTC, mcollina requested changes
We should be checking CORS in fetch() in Undici.

Could you please document this divergence from the spec instead?

2022-07-18 19:49 UTC, mcollina commented
We are not going to support CORS in Node.js.

2022-07-18 19:49 UTC, closed without merging