feat: implement (basic) webidl & headers comments
nodejs/undici pull request #1495
Opened 2022-06-14 23:46 UTC by KhafraDev

Fixes #933 

WebIdl is pretty cool and it's used rather heavily in the fetch spec. Implementing a subset of it (that we need) will make everything much easier once it's finished. I can explain how it'll help if you want, just don't want to write out an essay if you don't care lol

I only did the `Headers` class as a PoC and in the process discovered a *load* of bugs and decided just to add the spec comments since I was already adding a ton to it and fixing stuff anyways 😄.

p.s.: it's very clear that `HeadersList` was not supposed to be Map-like structure, as each key can be duplicated and the actual appending doesn't occur until you use `.get(...)`. Not a big deal, just something I noticed when working on it.

2022-06-15 03:38 UTC, ronag approved these changes

2022-06-15 07:01 UTC, mcollina requested changes
Could you add some tests for the new code?

2022-06-15 07:01 UTC, mcollina commented on lib/fetch/webidl.js
> +const { toUSVString } = require('util')
```suggestion
'use strict'

const { toUSVString } = require('util')
```

2022-06-15 15:06 UTC, mcollina approved these changes
lgtm

2022-06-15 15:06 UTC, mcollina requested changes
Could you add some tests for the new code?

2022-06-15 15:33 UTC, KhafraDev commented
added tests

2022-06-18 09:28 UTC, mcollina approved these changes
lgtm

2022-06-18 09:28 UTC, merged