Reset option
nodejs/undici pull request #1503
Opened 2022-06-20 11:06 UTC by ronag

2022-06-20 11:16 UTC, ronag commented
I can't make a test for this since Node server doesn't support keep alive with HEAD requests.

2022-06-20 12:47 UTC, mcollina requested changes
Good idea! tests are needed/missing.

2022-06-20 12:48 UTC, ronag commented on test/get-head-body.js
> +// })
Ideas?

2022-06-20 12:50 UTC, mcollina commented on test/get-head-body.js
> +// })
set `reset: false`.

We would also need another tests that do a `GET` with `reset: true`.

2024-06-28 18:12 UTC, DarkGL commented
Is this still needed ?

2024-06-29 06:40 UTC, ronag commented
Actually this is already implemented.

2024-06-29 06:40 UTC, closed without merging