fix(fetch): use AbortError DOMException
nodejs/undici pull request #1511
Opened 2022-06-23 03:57 UTC by KhafraDev

This commit uses the proper error when a request is aborted. A WPT actually checks for this behavior.

![image](https://user-images.githubusercontent.com/42794878/175205621-19010db2-a164-4d4d-856b-7ae3bbb0b3c7.png)

---

Honestly I didn't know if I should have put DOMException in constants or in util. I can change it if it matters or there's a preference.

2022-06-23 04:18 UTC, ronag approved these changes

2022-06-24 19:37 UTC, hebertcisco approved these changes

2022-06-26 10:38 UTC, LiviaMedeiros commented
Should this support user-provided `reason` and [`TimeoutError`](https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-timeout%E2%91%A0)?

2022-06-26 11:37 UTC, mcollina requested changes
Clearly marking that changes should br made here

2022-06-26 16:15 UTC, KhafraDev commented on lib/fetch/constants.js
> +const DOMException = globalThis.DOMException ?? (() => {
Somehow missed this notification 😕.

DOMException is available in node globally from v17 and above, but fetch supports v16.5 and above. There's a comment detailing why this is needed a few lines below.

2022-06-26 16:18 UTC, KhafraDev commented
> Should this support user-provided reason and [TimeoutError](https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-timeout%E2%91%A0)?

No, the spec requires an AbortError DOMException and the error is verbatim from Firefox's.

2022-06-26 16:40 UTC, LiviaMedeiros commented
> Clearly marking that changes should br made here

If you meant my question, it's completely not blocking. :)
Even if we decide that changes must be made, I believe it can be done in a follow-up PR instead.

> No, the spec requires an AbortError DOMException and the error is verbatim from Firefox.

Do we have any way to distinguish between arbitrary `AbortError` and `TimeoutError`? If not, I'm confused with how should [`AbortSignal.timeout()`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout) work in userland.

AFAIK there were common reasons in Node.js to use `AbortError` so `if (err.name === 'AbortError')` keeps being robust, but we definitely need a way to have more information. Is there a workaround?

This feature is not widely implemented yet, and timeout was added in Firefox only in v100 so its current behaviour doesn't convince me yet.

2022-06-26 17:16 UTC, KhafraDev commented
> Do we have any way to distinguish between arbitrary AbortError and TimeoutError? If not, I'm confused with how should [AbortSignal.timeout()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout) work in userland.

Yes, you can use the `.name` or `.code` property.

```js
const abortError = new DOMException('The operation was aborted.', 'AbortError')

abortError.name // 'AbortError'

abortError.code === DOMException.ABORT_ERR
```

> Do we have any way to distinguish between arbitrary AbortError and TimeoutError? If not, I'm confused with how should [AbortSignal.timeout()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout) work in userland.

There doesn't seem to be any discussion in the fetch spec repo, this should probably be followed up there.

- Firefox throws an AbortError DOMException.
- Chromium throws a TypeError (this is super wrong).

> AFAIK there were[1](https://github.com/nodejs/undici/pull/1511#user-content-fn-1-8ac4bf82061a5b7191b04fe46cb8bc8e)[2](https://github.com/nodejs/undici/pull/1511#user-content-fn-2-8ac4bf82061a5b7191b04fe46cb8bc8e) common reasons in Node.js to use AbortError so if (err.name === 'AbortError') keeps being robust, but we definitely need a way to have more information. Is there a workaround?

In the issue mentioned, `Node.js does throw DOMExceptions for DOM APIs.`. You can still use `error.name === 'AbortError'`.

2022-06-26 18:22 UTC, LiviaMedeiros commented
1. Providing custom `reason` to `AbortController.abort()`:
```mjs
const controller = new AbortController();
setTimeout(() => controller.abort('custom reason'), 10);

fetch('https://github.com/nodejs/undici/pull/1511', {
  signal: controller.signal
}).catch(err => {
  console.error(err.name, err.code, err.message, err.cause);
});
```

2. Using `AbortSignal.timeout()`:
```mjs
fetch('https://github.com/nodejs/undici/pull/1511', {
  signal: AbortSignal.timeout(10)
}).catch(err => {
  console.error(err.name, err.code, err.message, err.cause);
});
```

In both cases I'm getting generic `AbortError` `ABORT_ERR` `The operation was aborted` `undefined`.

As an user, in (1), I need to have a way to retrieve `custom reason`.
In (2), I need to have a way to retrieve `TimeoutError` (or Node.js-specific code with same meaning).

Is it retrievable without having an explicit reference to `signal.reason`? Should this be addressed in undici, or Node.js, or DOM specs?

```mjs
// This acknowledges TimeoutError in Node.js and Firefox >=100; Chrome <=102 doesn't support it
AbortSignal.timeout(10).addEventListener('abort', function(err) { console.info(this.reason.name) }); // TimeoutError
```

2022-06-26 19:16 UTC, KhafraDev commented
I'm getting the same results in the browser, this should be suggested at https://github.com/whatwg/fetch

2022-06-26 20:20 UTC, LiviaMedeiros approved these changes
Thanks, I'll go ahead and fill an issue to WHATWG.

Some references from brief searching:

- There is a seemingly related opened PR for `fetch` specs: https://github.com/whatwg/fetch/pull/1343
- PR which added `AbortSignal.timeout()` strongly emphasizes on ability to distinguish errors: https://github.com/whatwg/dom/pull/1032

My current impression (and suggestion to consider for undici implementation) on this is that having `error.cause == signal.reason` would be the best solution. But I might be wrong. :)

2022-06-26 22:34 UTC, mcollina commented on lib/fetch/constants.js
> +const DOMException = globalThis.DOMException ?? (() => {
You can get it with:

```js
try {
  atob('~')
} catch (err) {
  const DOMException = Object.getPrototypeOf(err).constructor

  console.log(new DOMException('aaa'))
}
```

2022-06-26 22:51 UTC, KhafraDev commented on lib/fetch/constants.js
> +const DOMException = globalThis.DOMException ?? (() => {
Done in edc4f540f7bdfb3a4f72bf9b2f742d8f9e6fbfb8

2022-06-27 07:18 UTC, mcollina approved these changes
lgtm

2022-06-27 07:23 UTC, merged