Fix fetch parameters not being applied correctly
nodejs/undici pull request #1870
Opened 2023-01-19 23:45 UTC by xconverge

Fixes https://github.com/nodejs/undici/issues/1864

2023-01-20 00:07 UTC, xconverge commented on lib/fetch/index.js
> -        headersTimeout: 300_000,
this would overwrite what was set in the agent a few lines up in ```const agent = fetchParams.controller.dispatcher```

2023-01-20 00:11 UTC, xconverge commented
Not sure how this directly undoes https://github.com/nodejs/undici/pull/1386 and the test still passes, will look into it and see if I am missing something obvious?

2023-01-20 08:31 UTC, mcollina commented
@ronag @KhafraDev why is `fetch()` completely overriding the agent options? I think it'd be best to stick to what is configured in the agent.

(I think I missed https://github.com/nodejs/undici/pull/1386, otherwise I would have objected then. It was a busy period of my life.).

2023-01-20 08:47 UTC, ronag requested changes
I think the fix here is simply that fetch doesn't pass it's own timeout values. Why do we override them in fetch?

2023-01-20 14:56 UTC, KhafraDev commented
They are overridden in fetch to match chrome's behavior. I agree that the fix is to remove them.

2023-01-20 16:01 UTC, xconverge commented
Do I need to adjust any defaults anywhere to preserve behavior or simply delete the 2 lines in lib/fetch/index.js? And remove my 300 sec test that was aiming to enforce the previous feature request?

2023-01-20 16:06 UTC, KhafraDev commented
removing the 2 lines is fine, along with the other changes

2023-01-20 16:29 UTC, xconverge commented
Ok this is ready for a re-review, it was my original changeset as well until I realized it was undo-ing #1373 and #1386

If you want me to add the 300 second tests back in from my previous commit and change the defaults elsewhere in the agent, please let me know, but for now at least the ability to override in fetch exists/works and a test that makes sure of that is in (unless the default gets changed to a much larger number in the future)

2023-01-20 16:57 UTC, xconverge commented
Oops sorry I didn't know clicking re-request review on a change request removes the other reviewers

2023-01-20 17:06 UTC, KhafraDev approved these changes

2023-01-20 17:29 UTC, mcollina approved these changes
lgtm

2023-01-20 17:29 UTC, merged

2023-01-25 20:14 UTC, xconverge commented
@mcollina @ronag what happens if you set bodyTimeout and headersTimeout to 20 minutes, but do NOT set keepAliveTimeout (default is 10 minutes), and a request takes say 15 minutes.

Looking at this code, it kind of looks to me like the request will just die and eventually timeout at the 20 minutes and return a bodyTimeout or headersTimeout. This is what I am experiencing (I know this is wack to have such long requests... but I am starting by just porting this request from axios which works)

```
    if (this.shouldKeepAlive && client[kPipelining]) {
      const keepAliveTimeout = this.keepAlive ? util.parseKeepAliveTimeout(this.keepAlive) : null

      if (keepAliveTimeout != null) {
        const timeout = Math.min(
          keepAliveTimeout - client[kKeepAliveTimeoutThreshold],
          client[kKeepAliveMaxTimeout]
        )
        if (timeout <= 0) {
          socket[kReset] = true
        } else {
          client[kKeepAliveTimeoutValue] = timeout
        }
      } else {
        client[kKeepAliveTimeoutValue] = client[kKeepAliveDefaultTimeout]
      }
    } else {
      // Stop more requests from being dispatched.
      socket[kReset] = true
    }
```

I will increase setting keepAliveTimeout but am wondering if there is a more elegant way to handle this so that the errors I get make sense

2023-01-25 21:08 UTC, mcollina commented
I'm failing to understand how that relates to this PR. If not, please open a new issue.

2023-01-25 22:25 UTC, xconverge commented
> I'm failing to understand how that relates to this PR. If not, please open a new issue.

Ok fair enough, I have little to no information to put in a new issue yet so was hoping to just get some guidance. I was hopeful that this PR fixed my long request issue and it does not, so to me there is something about undici that I continue to not understand for a long request. I am glad I was able to write a tangible test for this particular issue, so I will see if I can figure out how to write a test case for what I am still experiencing.

2023-01-26 17:33 UTC, xconverge commented
This is why I thought it was related, because it allowed me to expose the next issue basically https://github.com/nodejs/undici/issues/1887