use faster timers
nodejs/undici pull request #1908
Opened 2023-02-04 11:04 UTC by ronag

Another major bottleneck I found is the constant refreshing of timers, in particular the body timeout timer which is refresh every time we get a packet.

Our current use of timers is that we have a very few timers which we update frequently where high accuracy is not required. This PR tries to implement that.

2023-02-04 11:04 UTC, ronag commented
@mcollina This breaks all the tests using fake timers... thoughts on what to do about that?

2023-02-04 11:49 UTC, mcollina commented
What benefits is this giving us?

I would prefer this timer to be attached to the agent, so we can actually stop them. If this is significantly faster, why aren't we briging that optimization to Node.js itself?

2023-02-04 11:51 UTC, ronag commented
> What benefits is this giving us?

In high throughput scenarios with lots of small packets we are constantly calling `refresh` on node timers which is much more expensive than what this PR does.

> I would prefer this timer to be attached to the agent, so we can actually stop them. If this is significantly faster, why aren't we briging that optimization to Node.js itself?

I don't follow... Node has a more generic timer implementation which works for other less nisch use cases.

2023-02-04 12:01 UTC, ronag commented
@mcollina PTAL

2023-02-04 12:25 UTC, ronag commented
Note that the timers in this PR are *much* less accurate than note timers, which I believe is fine for our use case.

2023-02-04 12:26 UTC, mcollina commented
Have you got a benchmark before/after?

2023-02-04 12:42 UTC, ronag commented
Before:

[bench:run] │ undici - stream     │       1 │ 7383.29 req/sec │  ± 0.00 % │              + 395.85 % │

After:

[bench:run] │ undici - dispatch   │       1 │ 8045.52 req/sec │  ± 0.00 % │              + 380.21 % │

2023-02-04 16:17 UTC, anonrig commented on lib/client.js
> +const fastNowInterval = setInterval(() => {
When should we call clearInterval on this?

2023-02-04 18:35 UTC, mcollina commented
Note this is the same bottleneck of the slowloris mitigation we have in core. Works kind of the same too.

2023-02-04 18:35 UTC, mcollina commented
cc @ShogunPanda

2023-02-04 18:42 UTC, ronag commented
> Note this is the same bottleneck of the slowloris mitigation we have in core. Works kind of the same too.

slowloris?

2023-02-04 19:48 UTC, KhafraDev commented
> in particular the body timeout timer which is refresh every time we get a packet.

Rather than refreshing the timer, or making the timers less reliable (although not particularly important), it might be possible to let the timer run down, and re-calculate the delay based on the last packet received, or throw an error when the timer ends. Not sure if that sounds stupid or not lol

```js
lastPacketReceived = Date.now() // set on every packet

let timer = setTimeout(onBodyTimeout, bodyTimeout)

function onBodyTimeout () {
  if (Date.now() - lastPacketReceived >= bodyTimeout)
    throw ...

  timer = setTimeout(onBodyTimeout, bodyTimeout - (Date.now() - lastPacketReceived))
}

2023-02-04 20:11 UTC, mcollina requested changes

2023-02-04 20:11 UTC, mcollina commented on lib/client.js
> +}, 1e3)
This should be active only if there is an http going on. Given how this is implemented, every node process would get this timer.

2023-02-05 12:03 UTC, ShogunPanda commented
I wonder. Wouldn't be beneficial for undici to use the same connectionsCheckingInterval I introduced for node?
So we only have one timer on the server side and one on the client side.

2023-02-05 12:09 UTC, ronag commented
> I wonder. Wouldn't be beneficial for undici to use the same connectionsCheckingInterval I introduced for node? So we only have one timer on the server side and one on the client side.

Compared to the implementation of this PR? How is that better? Also, this would require node to expose it somehow publicly.

2023-02-05 12:10 UTC, ronag commented
I haven't looked into connectionsCheckingInterval so much. But would an alternative be the other way around? Go from a c++ version to an inaccurate but fast js version?

2023-02-05 12:14 UTC, ShogunPanda commented
Well, I guess you could try and measure the impact.

For you to consider: connectionsCheckingInterval is a mechanism that every x seconds check the entire pool of opened inbound connections comparing (in the same "inaccurate" way you did here) if the timeout as gone off.
He's written in C++ (leveraging C sorted sets and thus able to easily bail out early in the loop) but I think it can be easily adapted in JS. 

The only pain is to maintain the list of opened/active connections (especially when we think about KeepAlive)

2023-02-05 12:23 UTC, ronag commented
I see. I wouldn't mind using that per se. I don't know how that would practically work in undici which is developed outside of core.

2023-02-05 14:54 UTC, ronag commented
CI looks ok 👍

2023-02-05 14:56 UTC, ronag commented on lib/timers.js
> +  if (fastNowTimeout && fastNowTimeout.refresh) {
```suggestion
  if (fastNowTimeout && fastNowTimeout.refresh) {
    fastNow = Date.now()
```

2023-02-05 14:57 UTC, anonrig approved these changes

2023-02-05 14:58 UTC, ronag commented on lib/timers.js
> +    fastNow = Date.now()
```suggestion
```

2023-02-05 14:58 UTC, ronag commented on lib/timers.js
> +        refreshTimeout()
```suggestion
        refreshTimeout()
        fastNow = Date.now()
```

2023-02-05 16:11 UTC, mcollina approved these changes
lgtm

2023-02-05 16:11 UTC, mcollina commented
CI is still very red :(

2023-02-05 16:50 UTC, ronag commented
I will fix that

2023-02-05 18:59 UTC, ronag commented
Seems ok now. Same as usual with windows on node 19.

2023-02-05 19:15 UTC, merged

2023-02-05 20:48 UTC, KhafraDev commented
v12 CI failed on this test

```
     # Subtest: keep-alive threshold
        1..2
        ok 1 - should not error
        not ok 2 - (unnamed test)
          ---
          at:
            line: 217
            column: 13
            file: test/client-keep-alive.js
            type: Timeout
            method: _onTimeout
          stack: |
            Timeout._onTimeout (test/client-keep-alive.js:217:13)
          source: |2
                    const timeout = setTimeout(() => {
                      t.fail()
            ------------^
                    }, 2e3)
                    client.on('disconnect', () => {
          ...
        
        # failed 1 of 2 tests
    not ok 6 - keep-alive threshold # time=2017.2ms
```