fix: Allow “undefined“ as value in headers
nodejs/undici pull request #1929
Opened 2023-02-13 11:24 UTC by pan93412

https://github.com/nodejs/undici/pull/1896#discussion_r1104301293
Signed-off-by: pan93412 <pan93412@gmail.com>

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

KEY: S = Skipped, x = complete

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2023-02-13 11:25 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use tsd for our types.

2023-02-13 11:27 UTC, pan93412 commented
> Thanks for opening a PR! Can you please add a unit test? We use tsd for our types.

I make it a draft PR first – I am not sure if this is what @SimenB wants.

cc @SimenB for checking this PR

2023-02-13 12:02 UTC, SimenB commented
e.g.

```diff
diff --git i/test/types/dispatcher.test-d.ts w/test/types/dispatcher.test-d.ts
index 94c66ee3..cb50fc9a 100644
--- i/test/types/dispatcher.test-d.ts
+++ w/test/types/dispatcher.test-d.ts
@@ -14,6 +14,7 @@ expectAssignable<Dispatcher>(new Dispatcher())
   expectAssignable<boolean>(dispatcher.dispatch({ origin: '', path: '', method: 'GET' }, {}))
   expectAssignable<boolean>(dispatcher.dispatch({ origin: '', path: '', method: 'GET', headers: [] }, {}))
   expectAssignable<boolean>(dispatcher.dispatch({ origin: '', path: '', method: 'GET', headers: {} }, {}))
+  expectAssignable<boolean>(dispatcher.dispatch({ origin: '', path: '', method: 'GET', headers: { authorization: undefined } }, {}))
   expectAssignable<boolean>(dispatcher.dispatch({ origin: '', path: '', method: 'GET', headers: null, reset: true }, {}))
   expectAssignable<boolean>(dispatcher.dispatch({ origin: new URL('http://localhost'), path: '', method: 'GET' }, {}))
 
```

2023-02-13 12:44 UTC, pan93412 commented
request for review @SimenB @mcollina

2023-02-13 14:47 UTC, KhafraDev requested changes
Can you update the typescript version in package.json? `satisfies` was added in 4.9 while it currently matches >= 4.8.4

2023-02-13 14:58 UTC, pan93412 commented
Weird. Seems like I can only assign only one reviewer.

2023-02-13 15:04 UTC, KhafraDev approved these changes

2023-02-15 07:45 UTC, mcollina approved these changes
lgtm

2023-02-15 08:48 UTC, merged