Added diagnostics channels on fetch
nodejs/undici pull request #2210
Opened 2023-08-10 02:12 UTC by ida613

We added five diagnostics channels on fetch to trace the same information as would [tracingChannel.tracePromise](https://nodejs.org/api/diagnostics_channel.html#tracingchanneltracepromisefn-context-thisarg-args). Some channels won't make perfect sense but we want to stay consistent with [TracingChannel](https://nodejs.org/api/diagnostics_channel.html#class-tracingchannel) as we want to use it to trace fetch and maybe other functions when TracingChannel become available in the most commonly used versions of node.js. The descriptions of each channel and what gets published to them are detailed in DiagnosticsChannel.md

Use case: enable APM tools to trace fetch

2023-08-10 02:27 UTC, KhafraDev requested changes
It deviates from the spec, we've been careful to maintain a nearly 1:1 implementation and I don't think that this PR adds enough value to do so, sorry. I also have other concerns if the other maintainers think that we should move forward on this.

2023-08-10 08:04 UTC, metcoder95 reviewed
What are you concerns @KhafraDev? Just out of curiosity 🙂 

I enabled the CI to grasp the benchmarks, as I'm curious about the performance impact. The implementation produces roughly `14%` reduction, which is quite significative.
I imagine this is due to `diagnostic_channel` implementation.

<img width="860" alt="image" src="https://github.com/nodejs/undici/assets/10200776/917cc344-604e-469c-81ff-2a674b529ec2">

2023-08-10 08:04 UTC, metcoder95 commented on lib/fetch/index.js
> +function fetch (input, init = {}) {
Here we need to improve the wrapping to avoid deviate from spec

2023-08-10 08:27 UTC, mcollina commented
> It deviates from the spec, we've been careful to maintain a nearly 1:1 implementation and I don't think that this PR adds enough value to do so, sorry.

Why does it deviates from the spec? This is just information published on a node-only channel.

2023-08-10 14:44 UTC, KhafraDev commented
the actual implementation deviates from the spec (adds `innerFetch`, adds a new deferred promise/context object, etc.)

2023-08-10 14:47 UTC, KhafraDev commented
one of the biggest concerns is the end channel, which doesn't publish a message when the fetch ends, but is actually being done after a request has started:
```js
function fetch (input, init = {}) {
  const context = { input, init }
  if (channels.start.hasSubscribers) channels.start.publish(context)
  const promise = innerFetch(input, init, context)
  if (channels.end.hasSubscribers) channels.end.publish(context)
  return promise
}
```

I don't see a way of having this channel without a) allocating another promise, or b) further deviating from the spec

2023-08-10 19:14 UTC, ida613 commented
@KhafraDev the end channel gets published to at the end of the synchronous part of fetch, I know it doesn't make the most sense but we are trying to keep consistent with tracingChannel.tracePromise

2023-08-10 20:35 UTC, mcollina commented
> the actual implementation deviates from the spec (adds innerFetch, adds a new deferred promise/context object, etc.)

I don't understand this, does the spec mandates there should not be another function inside? Seems a bit prescriptive.

2023-08-10 21:51 UTC, KhafraDev commented
Yes it's prescriptive, but it makes maintaining fetch easier. For example, when the spec mentions "fetch", it will no longer be "fetch" in undici, but "innerFetch". Then there's also the added context argument which isn't required in the spec, but is now required in undici. Just things that will make maintaining it harder.

2023-08-11 00:24 UTC, ida613 commented
@KhafraDev thank you for bringing these concerns up! If it's any solace, all of this weirdness can be removed when tracing channel becomes available in the most commonly used versions of node.

2023-08-11 01:01 UTC, KhafraDev commented
which is years away from being stable and available in all LTS versions

2023-08-11 01:08 UTC, ida613 commented
TracingChannel

2023-08-11 07:57 UTC, mcollina commented
I don't think using TracingChannel adds anything to this topic, it will have the same identical issues that @KhafraDev has highlighted. The synchronous `end` event will be problematic anyway.

A solution to this issue is to _avoid_ creating a new `innerFetch` function, but rather emit the start event synchronously at the beginning of the function, and emit the end event right before returning, on all paths. This solution is more verbose but equivalent in term of coding. Wdyt?

2023-08-11 13:53 UTC, ida613 commented
Using TracingChannel we can keep the function like this:
```
async function fetch (input, init = {}) {
    return tracingChannel.tracePromise(() => {
      // regular fetch function with regular p = createDeferredPromise()
    }
  }
```
which avoids defining an innerFetch, passing in an extra argument and creating a new `createDeferredPromise` function.
Thank you for your proposed solution! I'll discuss with my team and get back to you ^ ^

2023-08-11 15:11 UTC, mcollina commented
That is identical to using `innerFetch` with the same problems spec-wise: you are creating an inner anonymous function within.

The solution is https://github.com/nodejs/undici/pull/2210#issuecomment-1674349576.

2023-08-11 18:09 UTC, Qard commented
> A solution to this issue is to _avoid_ creating a new `innerFetch` function, but rather emit the start event synchronously at the beginning of the function, and emit the end event right before returning, on all paths. This solution is more verbose but equivalent in term of coding. Wdyt?

The `end` event should match the point at which the function `synchronously` returns a value, which in this case is the promise. This means the correct place would actually be before the first await.

2023-08-11 18:28 UTC, mcollina commented
@Qard there is no await.

2023-08-11 18:33 UTC, Qard commented
Ah, then yes, the return would be the place for it. But then why is it marked as an async function? Does it need to be that way by the spec?

To ensure the end happens on all return branches, might be cleanest to wrap everything in a try/finally. 🤔

2023-08-11 18:42 UTC, KhafraDev commented
> Does it need to be that way by the spec?

it appears as though it shouldn't be async

2023-08-18 14:02 UTC, ida613 commented
Thank you so much for all the feedback! I'm putting this PR on hold for now and will work on it at a later date (probably within the next few months)

2024-02-26 23:23 UTC, Uzlopak commented
You mean like this?

https://github.com/nodejs/undici/pull/2857/commits/554f6f070acd5043eb36abcf655257cac977af7d

2024-03-07 11:20 UTC, mcollina commented
Closing in favor of https://github.com/nodejs/undici/pull/2701

2024-03-07 11:20 UTC, closed without merging