fix: adjust number of arguments in `Response.json()`
nodejs/undici pull request #2225
Opened 2023-08-25 19:45 UTC by LiviaMedeiros

`data` is not optional

Refs: https://fetch.spec.whatwg.org/#ref-for-dom-response-json

2023-08-25 20:03 UTC, ronag approved these changes

2023-08-25 21:26 UTC, KhafraDev requested changes
WPT fails because of this (the test was the reason for this change originally). Maybe the tests need to be updated.
```
Started \undici\test\wpt\tests\fetch\api\idlharness.any.js
{
  status: 1,
  name: 'Response interface: operation json(any, optional ResponseInit)',
  message: 'assert_equals: property has wrong .length expected 0 but got 1',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4534:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4527:22)\n' +
    '    at assert (evalmachine.<anonymous>:4511:19)\n' +
    '    at assert_equals (evalmachine.<anonymous>:1516:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1436:30)\n' +
    '    at IdlInterface.do_member_operation_asserts (evalmachine.<anonymous>:2363:5)\n' +
    '    at IdlInterface.<anonymous> (evalmachine.<anonymous>:2309:14)\n' +
    '    at Test.step (evalmachine.<anonymous>:2595:25)\n' +
    '    at IdlInterface.test_member_operation (evalmachine.<anonymous>:2257:12)\n' +
    '    at IdlInterface.test_members (evalmachine.<anonymous>:2720:26)'
}
```

2023-08-25 21:29 UTC, KhafraDev commented
yeah, it looks like the tests were updated at some point, https://wpt.fyi/results/fetch/api/idlharness.any.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=node.js&product=deno&aligned

2023-08-26 11:32 UTC, closed without merging

2023-08-26 11:32 UTC, mcollina commented
Can this be closed?

2023-08-26 11:48 UTC, LiviaMedeiros commented
Yes. https://github.com/nodejs/undici/pull/2226 contains the fix and `test/wpt/tests/fetch/api/idlharness.any.js` does the `length` assertions.