fix(types): responseHeaders typo in type
nodejs/undici pull request #2317
Opened 2023-10-07 23:35 UTC by vickvu

## This relates to...

N/A

## Rationale

The name of the field should be `responseHeaders`

## Changes

Change the field name to `responseHeaders`

### Features

N/A

### Bug Fixes

N/A

### Breaking Changes and Deprecations

N/A

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2023-10-11 16:28 UTC, Ethan-Arrowood approved these changes

2023-10-16 06:38 UTC, mcollina requested changes
Can you add a test for this? We use tsd to verify our types.

2023-10-23 06:49 UTC, kibertoad commented
@vickvu Do you need help with this?

2024-06-26 21:14 UTC, tsctx commented
Fixed by #3375

2024-06-26 21:14 UTC, closed without merging