simplify error and cause
nodejs/undici pull request #2347
Opened 2023-10-15 14:30 UTC by fedyk

This relates to https://github.com/nodejs/undici/pull/2327. Due to rebase of changes from master to next, the changes looks weird. I decided to create a new clean MR.

## Rationale

Since [Node v16.9.0](https://nodejs.org/api/errors.html#errorcause), `Error` supports `cause` property.

## Changes

Replace `Object.assign` with `new Error(.., { cause })`.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [s] Tested
- [s] Benchmarked (**optional**)
- [s] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2023-10-15 17:41 UTC, mcollina requested changes
I have a loose recall that v16.8 is what lambda deploys, so changing this would be detrimental.

2023-10-16 06:01 UTC, fedyk commented
@mcollina thanks for your comment.

I believe you are referring to AWS Lambda. According to the [docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html), they support Node.js `v16.x`. Brief grep in the [base nodejs image](https://github.com/aws/aws-lambda-base-images/tree/nodejs16.x), shows that the current version is `16.20.2` (they probably keep the most recent version live).

2023-10-16 07:59 UTC, metcoder95 approved these changes

2023-10-16 08:01 UTC, ronag commented
Can we make a test for node 16?

2023-10-16 08:21 UTC, mcollina commented
There is already one for node v16.8 in CI

2023-10-20 16:40 UTC, fedyk commented
If support of v16.8 is important, then those changes are breaking due to `cause` only available in v16.9. I believe this MR can be closed for now.

2023-10-20 16:40 UTC, closed without merging