Tests/websocket
nodejs/undici pull request #2553
Opened 2023-12-28 13:54 UTC by ilteoood

## This relates to...

#2267

## Rationale

Port websocket tests to node test runner

## Changes

Remove tap and use node test runner for the websocket suite

### Features

N/A

### Bug Fixes

N/A

### Breaking Changes and Deprecations

None

## Status

- [X] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [X] Tested
- [S] Benchmarked (**optional**)
- [S] Documented
- [X] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2023-12-28 14:14 UTC, ilteoood commented on test/websocket/opening-handshake.js
> +      const accept = createHash('sha1').update(key + uid).digest('base64')
These lines were already there

2023-12-28 19:51 UTC, mcollina approved these changes
lgtm

2023-12-28 19:58 UTC, KhafraDev requested changes
seems to have issues on windows

2023-12-29 11:13 UTC, ilteoood commented
@KhafraDev I've re-aligned everything with the main branch and tried to run the CI on my fork without changing anything: https://github.com/ilteoood/undici/actions/runs/7356075163/job/20025666784

It seems to be working

2023-12-29 20:34 UTC, KhafraDev commented
if it started working without change, it might be flaky. Not something I'd want to merge unless it was one-off.

2023-12-29 20:41 UTC, ilteoood commented
> if it started working without change, it might be flaky. Not something I'd want to merge unless it was one-off.

I've re-aligned with main before it started working, maybe is related to that. I have retried multiple times to retrigger it without luck

2023-12-30 23:25 UTC, mcollina commented
@KhafraDev you ok for this landing?

2023-12-30 23:31 UTC, merged