feat: port diagnostic-channel tests to node test runner
nodejs/undici pull request #2559
Opened 2023-12-29 12:09 UTC by ilteoood

## This relates to...

#2267

## Rationale

Port diagnostic-channel tests to node test runner

## Changes

Remove tap and use node test runner for the diagnostic-channel suite

### Features

N/A

### Bug Fixes

N/A

### Breaking Changes and Deprecations

None

## Status

- [X] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [X] Tested
- [S] Benchmarked (**optional**)
- [S] Documented
- [X] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2023-12-29 12:40 UTC, mcollina approved these changes
lgtm

2023-12-29 12:41 UTC, mcollina requested changes
The use of plan is an integral part of the test.

Use https://github.com/mcollina/tspl

2023-12-29 13:23 UTC, teobmg commented
@mcollina I've refactored a bit the tests in order to not rely anymore on plan, preserving its nature.
Let me know if I still need to use it.

2023-12-29 13:23 UTC, ilteoood commented
@mcollina I've refactored a bit the tests in order to not rely anymore on plan, preserving its nature.
Let me know if I still need to use it.

2023-12-29 13:32 UTC, mcollina commented
They are needed, because if no events are emitted, the tests will not fail.

2023-12-29 13:37 UTC, teobmg commented
> They are needed, because if no events are emitted, the tests will not fail.

If no events are emitted, the promise will never resolve so the test will go in timeout and then fail.
But got it, give me 10 minutes and I'll restore it

2023-12-29 13:50 UTC, teobmg commented
> They are needed, because if no events are emitted, the tests will not fail.

and now it's there!

2023-12-30 23:27 UTC, mcollina approved these changes
lgtm

2023-12-30 23:28 UTC, merged