Avoid structuredClone in Response()
nodejs/undici pull request #2617
Opened 2024-01-16 11:41 UTC by mcollina

Fixes https://github.com/nodejs/undici/issues/2615

Note that this is caused by https://github.com/nodejs/node/pull/51255 by @jasnell.
It can also be reproduced with:

```js
import { test } from 'node:test'
import assert from 'node:assert'

test('repro', async (t) => {
  const buf = new Uint8Array(1)
  const readable = new ReadableStream({
    start (controller) {
      controller.enqueue(buf)
      controller.close()
    }
  })

  const [out1, out2] = readable.tee()
  const cloned = structuredClone(out2, { transfer: [out2] })

  for await (const chunk of cloned) {
    assert.deepStrictEqual(chunk, buf)
  }

  for await (const chunk of out2) {
    assert.deepStrictEqual(chunk, buf)
  }

  for await (const chunk of out1) {
    assert.deepStrictEqual(chunk, buf)
  }
})
```

which will fail with:

```
✖ repro (5.626125ms)
  'Promise resolution is still pending but the event loop has already resolved'

ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 0
ℹ cancelled 1
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 8.293458

✖ failing tests:

test at file:/Users/matteo/Repositories/node/repro.mjs:6:1
✖ repro (5.626125ms)
  'Promise resolution is still pending but the event loop has already resolved'
```

2024-01-16 13:43 UTC, ronag approved these changes

2024-01-16 14:55 UTC, KhafraDev requested changes
This will cause the process to hang on v18 and v20

2024-01-16 15:01 UTC, mcollina commented
> This will cause the process to hang on v18 and v20

How? The tests are passing.

2024-01-16 15:27 UTC, mcollina commented
After a bit of digging, `structuredClone` was introduced in https://github.com/nodejs/undici/commit/4b30d4745e721cf5daedb64200e72ef2988dabb3, seemingly to pass a WPT test.

This was later fixed in https://github.com/nodejs/undici/commit/c7eb5f011cc87312eff67c6dc7deff119c093cb5 by adding an additional `.tee()`

However, the given WPT test is marked as [fail](https://github.com/nodejs/undici/blob/05797a517fca0091561e4ed5ee81937dd56c0ef6/test/wpt/status/fetch.status.json#L390-L395).

It does not seem we are losing anything by removing `structuredClone`, which is the source of the problem.

2024-01-16 15:38 UTC, KhafraDev commented
Ah right, I was mistaking it for something else related to this code. When the WPT runner fails a test, it doesn't cause the process to exist with an error (this was changed so it could run with node to report fetch test stats). While those 2 tests are passed as failing, a bunch of others aren't, and those are failing:

```
 Started /home/runner/work/undici/undici/test/wpt/tests/fetch/api/response/response-clone.any.js
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Int8Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Int16Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Int32Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Uint8Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Uint8ClampedArraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Uint16Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Uint32Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (BigInt64Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (BigUint64Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Float32Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buffer got disallowed value object "0,0,0,0"',
  stack: 'Error\n' +
    '    at get_stack (evalmachine.<anonymous>:4551:21)\n' +
    '    at new AssertionError (evalmachine.<anonymous>:4544:22)\n' +
    '    at assert (evalmachine.<anonymous>:4528:19)\n' +
    '    at assert_not_equals (evalmachine.<anonymous>:1542:9)\n' +
    '    at assert_wrapper (evalmachine.<anonymous>:1445:30)\n' +
    '    at evalmachine.<anonymous>:122:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  status: 1,
  name: 'Check response clone use structureClone for teed ReadableStreams (Float64Arraychunk)',
  message: 'assert_not_equals: Buffer of cloned response stream is a clone of the original buff [...]

2024-01-16 15:42 UTC, mcollina commented
> Ah right, I was mistaking it for something else related to this code. When the WPT runner fails a test, it doesn't cause the process to exst with an error (this was changed so it could run with node to report fetch test stats). 

I think our CI should catch a regression on WPT coverage (cc @panva).

2024-01-16 15:51 UTC, panva commented
> > Ah right, I was mistaking it for something else related to this code. When the WPT runner fails a test, it doesn't cause the process to exst with an error (this was changed so it could run with node to report fetch test stats).
> 
> I think our CI should catch a regression on WPT coverage (cc @panva).

No, undici's WPTs are [ran in undici](https://github.com/nodejs/node/pull/46498#issuecomment-1418201149), not nodejs/node.

What runs in node is a daily WPT Report which does not alert anyone on regressions given it also always pulls the latest WPT from web-platform-tests/wpt.

https://github.com/nodejs/citgm/pull/982 would run undici's checkout of WPTs

We could also add a github actions job in nodejs/node to run undici's fetch and WPT tests on every PR.

2024-01-16 15:53 UTC, panva commented
> When the WPT runner fails a test, it doesn't cause the process to exst with an error (this was changed so it could run with node to report fetch test stats).

@KhafraDev I don't recall such a change, necessity. I believe exit codes are irrelevant for the nodejs daily WPT job. https://github.com/nodejs/node/blob/main/.github/workflows/daily-wpt-fyi.yml#L114

2024-01-16 15:57 UTC, KhafraDev commented
Thanks for the clarification, maybe the change was made in node core to ignore the exit code and in undici to always exit with `0`? If it's being ignored in node it should be failing here, I'll look into it.

2024-01-16 16:25 UTC, panva commented
FWIW `process.exit(0)` was introduced in #2226

2024-01-17 00:44 UTC, weyert commented
Thank you. I have been trying to figure out how to make `undici` v6 work with jest and its `jsdom` environment but failed due to the use of `structuredClone` and wasn't able to stop `structuredClone` from being `undefined` in the tests. 

Downgraded to v5 for now. Hope to be able to switch back to v6 when a new release with this fix is out :)

2024-01-17 09:04 UTC, metcoder95 approved these changes

2024-01-17 09:53 UTC, mcollina commented
We are not landing this, instead we are reverting the problem in Node.js core.

2024-01-17 09:53 UTC, closed without merging