chore: refine esbuild & node detection
nodejs/undici pull request #2677
Opened 2024-01-31 07:33 UTC by mochaaP

When using the loader for external builtins, `esbuildDetection` is undefined. This commit defines `__UNDICI_IS_NODE__` on `globalThis` in the loader and deletes it after loading Undici. `esbuildDetection` has also been extracted as a variable at the top level of the module, to support deleting `__UNDICI_IS__NODE__` on `globalThis` to avoid polluting the global namespace.

Follow up of #2643.

2024-01-31 07:35 UTC, mochaaP commented
cc @khardix for https://bugzilla.redhat.com/show_bug.cgi?id=2261973

2024-01-31 08:53 UTC, metcoder95 approved these changes
LGTM, but I would like to have another pair of eyes from the team on this

2024-01-31 15:56 UTC, KhafraDev approved these changes
(same)

2024-02-01 03:54 UTC, Uzlopak commented on lib/fetch/index.js
> +const isNode = typeof __UNDICI_IS_NODE__ !== 'undefined' || typeof esbuildDetection !== 'undefined'
```suggestion
const defaultUserAgent = typeof __UNDICI_IS_NODE__ !== 'undefined' || typeof esbuildDetection !== 'undefined'
  ? 'node'
  : 'undici'
```

2024-02-01 03:54 UTC, Uzlopak commented on lib/fetch/index.js
> +    httpRequest.headersList.append('user-agent', isNode ? 'node' : 'undici', true)
```suggestion
    httpRequest.headersList.append('user-agent', isNode ? 'node' : 'undici', true)
```
```suggestion
    httpRequest.headersList.append('user-agent', defaultUserAgent, true)
```

2024-02-01 03:55 UTC, Uzlopak requested changes
I think my proposal is reasonable

2024-02-01 05:53 UTC, Uzlopak commented
@KhafraDev 
@metcoder95 

I wonder: In node 21, we have navigator.userAgent. Maybe in case of node, we should check if navigator.userAgent is set and use it, if not fallback to `nodejs/${process.versions.node.split('.')[0]}` ?

2024-02-01 05:53 UTC, Uzlopak approved these changes

2024-02-01 08:43 UTC, metcoder95 commented
>I wonder: In node 21, we have navigator.userAgent. Maybe in case of node, we should check if navigator.userAgent is set and use it, if not fallback to nodejs/${process.versions.node.split('.')[0]} ?

Yeah, that SGTM 👍 
But maybe even wait for Node v22

2024-02-01 10:11 UTC, mochaaP commented
> But maybe even wait for Node v22

I agree. We could merge this first and make the UA change in v7, since I consider this a breaking change?

2024-02-01 10:16 UTC, mcollina commented
I would like to avoid breaking changes for Node.js as much as possible, as it would create multiple release lines for us to maintain and backport security fixes.

That's inescapable, so breaking changes will be batched. I'm not sure we would do a undici v7 before Node.js v22 is out, as it mostly depend on the amount of changes we want to ship.

2024-02-01 10:20 UTC, mochaaP commented
IMO, it's not _that_ important to change the UA. I couldn't think of possible benefits for changing the user agent, except for collecting metrics for node.js versions.

2024-02-01 10:21 UTC, Uzlopak commented
Yeah, lets not open that can of worms.

2024-02-01 11:21 UTC, mochaaP commented
Once this lands, we'd be happy to backport this in Fedora.

2024-02-01 16:13 UTC, mcollina approved these changes
lgtm

2024-02-01 16:13 UTC, mcollina commented
I'll land this after the security release.

2024-02-09 01:25 UTC, mochaaP commented
Hi @mcollina, seems this got missed in the security release?

2024-02-09 17:41 UTC, merged

2024-02-09 17:42 UTC, mcollina commented
The goal was to land it _after_ the release.