chore: improve usage of skip in tests
nodejs/undici pull request #2761
Opened 2024-02-14 17:28 UTC by Uzlopak

This is an opinionated change. I like to see in the test runner output if a test was skipped or not. So it is possible to see how many of the tests were skipped. If we just call skip and then process.exit() it does not show that we skipped 1 or 10 tests.

Also removed version check for node 16.

2024-02-14 18:11 UTC, KhafraDev requested changes

2024-02-14 18:11 UTC, KhafraDev commented on test/cookie/global-headers.js
> +const skip = !globalThis.Headers
We can remove this entirely, Headers exists in node >= 18

2024-02-14 18:11 UTC, KhafraDev commented on test/gc.js
>    typeof FinalizationRegistry === 'undefined' ||
both of these can be removed

2024-02-14 18:11 UTC, KhafraDev commented on test/node-test/diagnostics-channel/connect-error.js
>  }
this can be removed

2024-02-14 18:11 UTC, KhafraDev commented on test/node-test/diagnostics-channel/error.js
> +  skip = true
same here

2024-02-14 18:11 UTC, KhafraDev commented on test/node-test/diagnostics-channel/get.js
>  }
same here

2024-02-14 18:11 UTC, KhafraDev commented on test/node-test/diagnostics-channel/post-stream.js
>  }
and here

2024-02-14 18:11 UTC, KhafraDev commented on test/node-test/diagnostics-channel/post.js
>  }
and here

2024-02-14 18:41 UTC, Uzlopak commented
@KhafraDev PTAL

2024-02-14 18:46 UTC, KhafraDev approved these changes

2024-02-14 20:58 UTC, metcoder95 approved these changes

2024-02-16 21:13 UTC, Ethan-Arrowood approved these changes
nice, lgtm

2024-02-17 07:02 UTC, mcollina approved these changes
lgtm

2024-02-17 07:03 UTC, merged