fix: MockResponseCallbackOptions type
nodejs/undici pull request #2951
Opened 2024-03-12 18:47 UTC by merojosa

## This relates to...
https://github.com/nodejs/undici/issues/1583

## Rationale

The issue is self-explanatory. It's kinda complicated to get what the actual types are. So I decided to print the `opts`argument:
https://github.com/nodejs/undici/blob/0b5a4515f3b7c0bbdc873ea172c47a56e515b167/lib/mock/mock-interceptor.js#L124

This is what I got:

![image](https://github.com/nodejs/undici/assets/38768936/17df3dd4-7bde-4ce9-ac97-c7e6bf00d0b5)
![image](https://github.com/nodejs/undici/assets/38768936/2a07d43d-a309-42e6-bcda-9e71633cc310)

From what I understand, only  `path` and `method` are sure to exist.

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-03-12 20:22 UTC, metcoder95 reviewed
Can you add some testing to it?

2024-03-21 09:38 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use tsd for types

2024-05-05 08:51 UTC, metcoder95 approved these changes

2024-05-06 12:33 UTC, mcollina approved these changes
lgtm

2024-05-06 12:33 UTC, merged