fix: count for error response and network errors
nodejs/undici pull request #2966
Opened 2024-03-15 11:15 UTC by metcoder95

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-03-15 11:44 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-03-18 08:56 UTC, mcollina approved these changes
lgtm

2024-03-18 08:56 UTC, mcollina commented
there is a conflict now, can you fix it?

2024-03-19 14:00 UTC, acommodari commented on lib/handler/retry-handler.js
> +        : Math.min(minTimeout * timeoutFactor ** counter, maxTimeout)
if counter starts at 1 should this not be (counter - 1)? This way the first retry uses the `minTimeout` value?

2024-03-19 14:00 UTC, acommodari commented on lib/handler/retry-handler.js
> +        : Math.min(minTimeout * timeoutFactor ** counter, maxTimeout)
right now it would start at double the original minTimeout

2024-03-21 09:38 UTC, mcollina approved these changes
lgtm

2024-03-21 09:38 UTC, merged