fallback to Buffer.isUtf8 on platforms without icu
nodejs/undici pull request #3006
Opened 2024-03-27 16:24 UTC by KhafraDev

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-03-27 16:34 UTC, metcoder95 commented on lib/web/websocket/util.js
> +        process.emitWarning('ICU is not supported and no fallback exists. Please upgrade to at least Node v18.14.0.', {
Shall we reduce the emits to just `once`?

2024-03-27 18:21 UTC, mcollina requested changes
we need tests

2024-03-27 18:59 UTC, KhafraDev commented
https://github.com/nodejs/undici/issues/3002#issuecomment-2022910249

In the meantime, if this doesn't work I don't think there's any harm. WebSocket doesn't currently work for those using node without ICU. There isn't a case where it'll allow invalid utf-8: if someone's node version is without icu and doesn't support buffer.isUtf8, an error is thrown.

2024-03-28 04:43 UTC, KhafraDev commented
@mcollina I confirmed locally that this PR works on a --without-intl build. Tbh I think I'll end up upstreaming this change so TextDecoder in the non-icu build can also use the fatal option.

2024-03-28 23:38 UTC, mweberxyz commented
FWIW- I used this branch as a test for my in-progress automated `--without-intl` CI branch and undici tests (both in main and this branch) are still failing.

See: https://github.com/mweberxyz/nodejs-undici/actions/runs/8474734954/job/23221671648?pr=5

2024-03-29 06:38 UTC, mweberxyz commented
FWIW - also passes my proposed automated w/o intl ci checks: https://github.com/mweberxyz/nodejs-undici/pull/7

2024-03-29 07:13 UTC, Uzlopak commented on lib/web/websocket/util.js
> +function utf8Decode (buffer) {
const utf8Decode = hasIntl ? fatalDecode.decode
: etc.

2024-03-29 07:20 UTC, mcollina approved these changes
lgtm with others comments fixed

2024-04-04 09:51 UTC, merged