fix: don't leak internal class
nodejs/undici pull request #3024
Opened 2024-03-31 07:45 UTC by ronag

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-03-31 08:39 UTC, ronag commented
The messages here are weird, `:headers` isn't actually headers it's response

2024-03-31 10:38 UTC, metcoder95 commented
Shall we point to `next`?

2024-03-31 10:42 UTC, ronag commented on types/diagnostics-channel.d.ts
> +    headers: Array<Buffer>;
```suggestion
    headers: string;
```

2024-03-31 11:14 UTC, ronag commented on types/diagnostics-channel.d.ts
> +    headers: string;
```suggestion
    headers: any;
```

2024-03-31 13:10 UTC, mcollina requested changes
The goal is to leak the internal class, so it could be used as key in maps etc.

2024-03-31 13:38 UTC, ronag commented
That's a bad idea in my opinion and can lead to all kinds of undefined behaviors and breaking. The internal class has no guarantees to its interface.

2024-03-31 13:39 UTC, ronag commented
> The goal is to leak the internal class, so it could be used as key in maps etc.

I don't see how this PR would change it. You can still use the passed object as a key.

2024-03-31 14:27 UTC, mcollina approved these changes
lgtm

I missed that

2024-04-01 08:08 UTC, metcoder95 approved these changes

2024-04-01 09:00 UTC, merged