feat: add onStart hook
nodejs/undici pull request #3028
Opened 2024-03-31 12:42 UTC by ronag

Part of a larger overhauld of hooks. This on is not breaking and can therefore land earlier.

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-03-31 13:14 UTC, mcollina requested changes

2024-03-31 13:14 UTC, mcollina commented on test/node-test/client-dispatch.js
> -        dispatches.push('onResponseStarted')
Can you add a test that keeps showing this behavior? Or add a new test for onStart?

2024-04-03 10:02 UTC, metcoder95 approved these changes
LGTM, shall we document it and add types for it?

2024-04-03 10:02 UTC, metcoder95 commented on lib/core/request.js
> +      // Compatibility with the old API.
Shall we add it to the major checklist?

2024-04-03 10:34 UTC, ronag commented on lib/core/request.js
> +      // Compatibility with the old API.
Already on the list to remove.

2024-04-03 13:26 UTC, ronag commented
Updated according to feedback from @BridgeAR

2024-04-04 10:58 UTC, closed without merging