test: duplicate jest unspecific tests to native runner
nodejs/undici pull request #3075
Opened 2024-04-09 01:12 UTC by Uzlopak

the touched two test files have no jest specific tests. Transforming them to normal tests.

2024-04-09 02:28 UTC, KhafraDev requested changes
the tests are specific to jest, to make sure undici works with it

2024-04-09 06:18 UTC, mcollina approved these changes
lgtm

2024-04-09 23:47 UTC, Uzlopak commented
@KhafraDev 
I checked it. Those two tests have nothing jest specific. they seem to be implemented in jest, because the corresponding dev was fluent in jest but not in tap.

See:
#1757
#1338

The issues have no jest specific information.

2024-04-10 00:26 UTC, KhafraDev commented
#1757 was implemented by me and I am not fluent in jest, but I'll take the compliment. There's a comment in the PR about why I used jest for it.

2024-04-10 00:37 UTC, Uzlopak commented
ok the reason for #1757 hidden in https://github.com/nodejs/undici/issues/1756#issuecomment-1304645670

What about the interceptor.js? does it contain jest specific tests?

2024-04-10 23:37 UTC, Uzlopak commented
I discussed this with Khafra about this. We duplicate the tests as they are relevant for both: the regular test set and for the jest compatibility.

2024-04-11 22:27 UTC, KhafraDev approved these changes

2024-04-11 22:27 UTC, merged