docs: add directions to run docs and benchmarks
nodejs/undici pull request #3092
Opened 2024-04-11 14:15 UTC by FatumaA

## This relates to...

Closes #3004 

## Rationale

Adds directions on how to run benchmarks and the docs as it wasn't clear.

## Changes

Added links to the contributing guide and relevant sections showing what commands to run and what to expect.

### Features

N/A

### Bug Fixes

N/A

### Breaking Changes and Deprecations

N/A

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [x] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-04-13 16:24 UTC, Uzlopak commented on CONTRIBUTING.md
>  <a id="developers-certificate-of-origin"></a>
I think this must be above the corresponding header

2024-04-13 16:25 UTC, Uzlopak requested changes
I think the ankers are wrong positioned.

2024-04-13 16:47 UTC, FatumaA commented
> I think the ankers are wrong positioned.

You are right, I'll look into it

2024-04-13 20:54 UTC, Uzlopak approved these changes
I fixed the issues I remarked because this PR had merge conflicts, and while fixing those I did them too.

2024-04-14 08:36 UTC, metcoder95 approved these changes

2024-04-14 09:52 UTC, mcollina requested changes
There are many changes that are unrelated. Can you revert them?

2024-04-14 09:56 UTC, FatumaA commented
> There are many changes that are unrelated. Can you revert them?

Must be auto formatter

I can't get to it till Monday though

2024-04-15 08:56 UTC, FatumaA commented
Should be ok now

2024-04-15 13:33 UTC, mcollina approved these changes
lgtm

2024-04-15 13:52 UTC, merged