Issue 3136
nodejs/undici pull request #3137
Opened 2024-04-19 09:10 UTC by ronag

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-04-19 09:11 UTC, ronag commented
@sandratatarevicova  Do you think you can help create a test that does not depend on external url?

2024-04-19 09:42 UTC, mcollina requested changes

2024-04-19 09:42 UTC, mcollina commented on test/issue-3136.js
> +request('http://www.rolbox.it/rk-kastelruth/webcam/web03.jpg', { throwOnError: true })
This needs a server, we can't use an external url

2024-04-19 09:43 UTC, metcoder95 reviewed
LGTM, just waiting for tests around it

2024-04-19 10:36 UTC, sandratatarevicova commented
> @sandratatarevicova Do you think you can help create a test that does not depend on external url?

Thank you! I have modified the test in https://github.com/sandratatarevicova/undici/commit/d9183af7357517d91325315165c49a9330823f27. Should I create a PR to your branch?

2024-04-19 10:38 UTC, ronag commented
@sandratatarevicova if you don't min I'll just copy it into this PR

2024-04-19 12:16 UTC, mcollina approved these changes
LGTM

2024-04-21 08:56 UTC, metcoder95 approved these changes

2024-04-21 08:56 UTC, merged