perf: use class instead of object literals with getters
nodejs/undici pull request #3138
Opened 2024-04-19 12:49 UTC by tsctx

Slow initialization of object literals with getters.

- main
```
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)  12'398 ns/iter   (8'100 ns … 4'134 µs) 11'000 ns 34'100 ns    147 µs
```

- this patch

```
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)  10'997 ns/iter   (7'000 ns … 3'704 µs)  9'700 ns 34'000 ns    159 µs
```

2024-04-19 14:23 UTC, mcollina approved these changes
lgtm

2024-04-19 14:28 UTC, Uzlopak commented
Did you also see that makePolicyContainer() seemed to be super slow?

2024-04-19 19:34 UTC, KhafraDev requested changes
This should be done for all classes (there is no such thing as a "Request Realm Settings Object", there *is* an "Environment Settings Object").

2024-04-19 19:35 UTC, KhafraDev commented
> Did you also see that makePolicyContainer() seemed to be super slow?

It returns an object with a single property. If you're running creating a hundred thousand Requests everything will seem to be "super slow".

2024-04-20 08:42 UTC, mcollina commented
There is nothing absolutely “slow” or “fast”, as those are relative concepts. The only useful measure when doing optimization work is to identify bottlenecks and remove them.

(A tiny fast function called a bazillion times might be causing a bottleneck as much as a huge slow function seldomly called).

2024-04-20 14:11 UTC, KhafraDev commented
not in this context, it's called once per Request and is needed for spec compatibility

2024-04-20 15:37 UTC, tsctx commented
> not in this context, it's called once per Request and is needed for spec compatibility

What do you mean by that?  I've already created a new context for each call.

2024-04-20 17:53 UTC, KhafraDev commented
I was responding to Matteo's comment, nothing to do with this PR

2024-04-20 17:55 UTC, KhafraDev requested changes
Response has a realm also, which is an Environment Settings Object.

We're also adding a realm to Headers in some cases but it's unused, should probably be removed.

2024-04-20 22:31 UTC, tsctx commented
@KhafraDev ptal

2024-04-20 23:07 UTC, tsctx commented on lib/web/fetch/request.js
> +    // TODO: Remove workaround.
```suggestion
```

2024-04-20 23:14 UTC, KhafraDev commented
EnvironmentSettingsObject should be shared between Response and Request, it's meant to be the same object. It's fine to lazily create the properties needed for each.

2024-04-21 00:59 UTC, tsctx commented
> I guess that can lead to further perf improvements, the `realm` should be the exact same object and it can't change because they're non-transferable and cannot be cloned. The issue there being that the global origin may be mutated, but that can be a getter while policyContainer and whatever else is constant?

If we use getter, there should be no problem.

2024-04-21 01:20 UTC, KhafraDev approved these changes

2024-04-21 01:22 UTC, KhafraDev requested changes
Sorry, it seems like baseUrl is only set once. It can be set whenever so it should update appropriately.

2024-04-21 01:24 UTC, tsctx commented on lib/web/fetch/util.js
> +  }
```suggestion
  baseUrl =  getGlobalOrigin()
```

2024-04-21 01:24 UTC, tsctx commented on lib/web/fetch/util.js
> +  baseUrl =  getGlobalOrigin()
```suggestion
  baseUrl = getGlobalOrigin()
```

2024-04-21 01:25 UTC, KhafraDev commented
I don't think that those changes will solve the issue, consider the following:

```mjs
import { setGlobalOrigin, Response } from 'undici'

setGlobalOrigin('http://localhost:3000')
new Request('/').url // http://localhost:3000

setGlobalOrigin('https://www.google.com')
new Request('/').url // https://www.google.com
```

If this works, please add a test so we don't regress in the future.

2024-04-21 01:29 UTC, tsctx commented
> I don't think that those changes will solve the issue, consider the following:
> 
> ```js
> import { setGlobalOrigin, Request } from 'undici'
> 
> setGlobalOrigin('http://localhost:3000')
> new Request('/').url // http://localhost:3000
> 
> setGlobalOrigin('https://www.google.com')
> new Request('/').url // https://www.google.com
> ```
> 
> If this works, please add a test so we don't regress in the future.

It works correctly before and after the change.

2024-04-21 01:32 UTC, KhafraDev approved these changes
I see why, didn't realize a new object was being created every time. We should be able to reuse a single instance of `EnvironmentSettingsObject` instead of creating a new realm per Request/Response. This PR is fine to land as-is, I've already made you do enough...

2024-04-21 01:33 UTC, merged