websocket: optimize masking using WebAssembly
nodejs/undici pull request #3273
Opened 2024-05-17 11:20 UTC by tsctx

Closes #3265 

I have created `ws-masking` which allows fast masking in WebAssembly.

I marked this feature as experimental and not available without a flag.

Package details are in https://github.com/tsctx/ws-masking

- main

```
• send
------------------------------------------------- -----------------------------
ws          1'958 µs/iter   (1'672 µs … 6'897 µs)  1'956 µs  4'460 µs  6'897 µs
undici      1'926 µs/iter   (1'667 µs … 6'695 µs)  1'942 µs  3'954 µs  6'695 µs

summary for send
  undici
   1.02x faster than ws
```

- this PR

```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• send
------------------------------------------------- -----------------------------
ws          1'880 µs/iter   (1'587 µs … 6'713 µs)  1'870 µs  4'768 µs  6'713 µs
undici        901 µs/iter     (639 µs … 5'268 µs)    917 µs  3'044 µs  5'268 µs

summary for send
  undici
   2.09x faster than ws
```

2024-05-17 11:21 UTC, tsctx commented on benchmarks/websocket/websocket-send-buffer.mjs
TODO: delete this file

2024-05-17 11:38 UTC, tsctx commented
@mcollina If you wish, we will invite you to be a collaborator.

2024-05-17 13:58 UTC, KhafraDev requested changes
I don't think this is the right way for WebSocket to move in.

2024-05-17 16:10 UTC, tsctx commented
closed/

2024-05-17 16:10 UTC, closed without merging

2024-05-17 23:14 UTC, KhafraDev commented
@lpinca I'm not sure if you'd be interested in this or not.

2024-05-18 05:25 UTC, lpinca commented
It is nice for portability but `bufferutil` seems to be faster in all cases.

2024-05-18 06:59 UTC, tsctx commented
Since it must be copied to the memory area, bufferutil, which does not copy, has the advantage.

2024-05-18 08:06 UTC, lpinca commented
Now that `WebSocket` is in Node.js core, we could add a `Buffer.mask()` and `Buffer.unMask()` implementation using SIMD instructions and exposing it for public usage similarly to how it was done for `Buffer.isUtf8()`.

cc: @lemire @anonrig

2024-05-19 09:57 UTC, tsctx commented
There is a big wall...
* Node
```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• send
------------------------------------------------- -----------------------------
undici      1'873 µs/iter   (1'530 µs … 4'230 µs)  1'946 µs  3'709 µs  4'230 µs

summary for send
  undici
```
* Node (with PR)
```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• send
------------------------------------------------- -----------------------------
undici        805 µs/iter     (500 µs … 3'027 µs)    851 µs  1'434 µs  3'027 µs

summary for send
  undici
```
* Node (with zero mask)
```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• send
------------------------------------------------- -----------------------------
undici        726 µs/iter     (454 µs … 2'701 µs)    819 µs  1'769 µs  2'701 µs

summary for send
  undici
```
* Bun
```
benchmark      time (avg)             (min … max)       p75       p99      p999     
------------------------------------------------- -----------------------------     
• send
------------------------------------------------- -----------------------------     
global        380 µs/iter     (302 µs … 1'812 µs)    371 µs  1'426 µs  1'801 µs

summary for send
  global
```
* Deno
 ```
benchmark      time (avg)             (min … max)       p75       p99      p999     
------------------------------------------------- -----------------------------     
• send
------------------------------------------------- -----------------------------     
global        480 µs/iter     (388 µs … 1'120 µs)    499 µs    738 µs    986 µs

summary for send
  global
```

2024-05-19 14:20 UTC, lemire commented
@lpinca Can you provide the specification for the functions?

2024-05-19 16:06 UTC, KhafraDev commented
https://datatracker.ietf.org/doc/html/rfc6455#section-5.3

2024-05-19 18:45 UTC, lpinca commented
@lemire for a possible API see https://github.com/websockets/bufferutil?tab=readme-ov-file#bufferutilmasksource-mask-output-offset-length. The last 3 parameters can be optional.

2024-05-19 19:24 UTC, lemire commented
@lpinca @KhafraDev  Thanks.