websocket: use linkedlist insteadof Set
nodejs/undici pull request #3283
Opened 2024-05-21 06:54 UTC by tsctx

@KhafraDev

2024-05-21 09:16 UTC, mcollina approved these changes
lgtm

2024-05-21 11:49 UTC, tsctx commented
> Why not `fixed_queue` from node core?

There is no particular reason for this.

2024-05-21 12:10 UTC, ronag commented
> In this use case, I prefer the simple linkedlist; Initialization of the array of 2048 entries takes time :)

I think that is amortized quite quickly...

2024-05-21 13:36 UTC, tsctx commented
> do you have benchmarks?

What about?

2024-05-21 13:38 UTC, tsctx commented
If it was about sending data, it would be 1.2 times faster since we changed to zero-copy.

2024-05-21 13:40 UTC, KhafraDev commented
Yeah, sending messages. Do you have the data to backup the 1.2x faster claim?

2024-05-21 13:47 UTC, tsctx commented
okey, look this

```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• send
------------------------------------------------- -----------------------------
undici      1'467 µs/iter   (1'187 µs … 6'165 µs)  1'442 µs  4'022 µs  6'165 µs <- before
undici      1'658 µs/iter   (1'305 µs … 4'145 µs)  1'673 µs  3'043 µs  4'145 µs <- after
```

2024-05-21 13:56 UTC, tsctx commented
> > In this use case, I prefer the simple linkedlist; Initialization of the array of 2048 entries takes time :)
> 
> I think that is amortized quite quickly...

Rewrite with fixed_queue!

2024-05-21 14:14 UTC, KhafraDev approved these changes
why is queue being lazily created?

2024-05-21 14:15 UTC, KhafraDev requested changes
tests are failing

2024-05-21 14:28 UTC, tsctx commented
I don't have time right now, so I will rewrite it in another PR.

2024-05-21 22:20 UTC, KhafraDev commented on lib/web/websocket/sender.js
> +  #queue = null
```suggestion
  /**
   * @type {FixedQueue}
   */
  #queue = new FixedQueue()
```

2024-05-21 22:20 UTC, KhafraDev commented on lib/web/websocket/sender.js
> +        }
```suggestion
```

2024-05-21 22:20 UTC, KhafraDev commented on lib/web/websocket/sender.js
> +    }
```suggestion
```

2024-05-21 22:25 UTC, tsctx commented on lib/web/websocket/sender.js
> +    /** @type {FixedQueue} */
```suggestion
```

2024-05-21 22:27 UTC, tsctx commented on lib/web/websocket/sender.js
```suggestion
```

2024-05-21 22:29 UTC, KhafraDev commented
Thanks, WebSocket is bidirectional so it doesn't make sense to only be receiving messages (which is the only benefit I can see in lazily creating the queue?). We also have EventSource for that use case.

2024-05-21 22:35 UTC, tsctx commented
When I received the message, I mistakenly thought I was generating a queue.

So there is no advantage.

2024-05-22 01:18 UTC, KhafraDev approved these changes

2024-05-22 02:04 UTC, merged