feat: add dns cache
nodejs/undici pull request #3349
Opened 2024-06-20 10:55 UTC by DarkGL

## This relates to...

https://github.com/nodejs/undici/pull/2552

## Rationale

This is version of dns cache with resolved merge conflicts and tests moved to `node:test` , most of the work is done by @antoinegomez

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-06-20 11:11 UTC, DarkGL commented
I need help with fixing test on mac os (works on windows and linux)

Test:

`
test('http example', async (t) => {
  t = tspl(t, { plan: 1 })

  const cacheable = new DNSResolver({ resolver })

  const options = {
    hostname: 'example',
    port: 9999,
    lookup: cacheable.lookup
  }

  await t.rejects(makeRequest(options), {
    message: 'connect ECONNREFUSED 127.0.0.127:9999'
  })
})

const makeRequest = (options) =>
  new Promise((resolve, reject) => {
    http.get(options, resolve).once('error', reject)
  })
`

on mac os this test fails with:

`
✖ test/dns-resolver.js (30015.227ms)
  'test timed out after 30000ms'
`

on windows and linux this test resolves correctly

2024-06-20 11:19 UTC, ronag commented on README.md
> +  dnsResolver: new MyCustomDNSResolver()
Why this? I believe using the existing connect option should be sufficient?
```suggestion
  connect: { lookup: myCustomDNSResolverLookup }
```

2024-06-20 11:20 UTC, ronag requested changes
I don't think this is necessary. Already possible:

```js
import CacheableLookup from 'cacheable-lookup';

const cacheable = new CacheableLookup(opts)

const agent = new Agent({
  connect: { lookup: cacheable.lookup }
})

2024-06-20 11:36 UTC, DarkGL commented
Mentioning reviewers from orginal pr @mcollina @ShogunPanda @metcoder95 @KhafraDev

2024-06-20 17:41 UTC, KhafraDev commented
As ronag mentioned it's already possible to use cacheable-lookup

2024-06-20 17:42 UTC, KhafraDev commented
The only reason I could see for adding it is if we wanted to enable it by default, but we're probably better off just documenting it

2024-06-21 01:22 UTC, DarkGL commented
Should we add it here https://github.com/nodejs/undici/tree/main/docs/examples or https://github.com/nodejs/undici/tree/main/docs/docs/best-practices ?

2024-06-21 06:12 UTC, ronag commented
Examples

2024-06-21 10:42 UTC, closed without merging