fix: retry handler provide invalid with fetch
nodejs/undici pull request #3365
Opened 2024-06-24 10:23 UTC by climba03003

## This relates to...

Fixes #3356 

## Rationale

`RetryHandler` should buffer the body instead of streaming to the next handler.
The reason behind is that the body maybe used by the next handler immediately and leads to stacking multiple invalid response.

## Changes

Buffer the body until the response is success or error.
It should result on all status code that is not `206` to retain the current behavior.

### Features

### Bug Fixes

### Breaking Changes and Deprecations

I though it may increase in memory usage for non-fetch people, because the payload can be streamed before but not now.
But in order to retain the correct behavior for retry, buffering should happen.

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-06-24 10:45 UTC, climba03003 commented
Test failure seems unrelated to the PR, it failed to download `Node.js`.

2024-06-24 11:44 UTC, ronag requested changes
We should not be buffering in memory.

2024-06-25 07:52 UTC, metcoder95 reviewed
Let's better throw, is safer and imposes less overhead, wdyt?

2024-06-25 13:33 UTC, mcollina commented
Yes

2024-07-03 10:33 UTC, climba03003 commented
See #3389

2024-07-03 10:33 UTC, closed without merging