fix(websocket): use binary operations instead of a Set for closeStatus
nodejs/undici pull request #3635
Opened 2024-09-21 00:26 UTC by Uzlopak

Follow up to #3628

2024-09-21 05:55 UTC, KhafraDev requested changes
> It's possible to avoid the set *but nothing here is a hot path - websockets are not closed often.*

It's not worth the mental overhead. The websocket closing handshake is an extremely cold path.

2024-09-21 07:48 UTC, Uzlopak commented
Using a Set is an unconventional and to honest very ugly Implementation in our codebase. I strongly recommend to avoid ES6 Sets to just store 2 bit information...

2024-09-21 08:40 UTC, Uzlopak commented on lib/web/websocket/websocket.js
> +    const wasClean = this.#handler.closeState === (sentCloseFrameState.SENT & sentCloseFrameState.RECEIVED)
```suggestion
    const wasClean = this.#handler.closeState === (sentCloseFrameState.SENT | sentCloseFrameState.RECEIVED)
```

2024-09-23 15:51 UTC, KhafraDev commented
I don't agree with any of that. The implementation is easy to understand and not in a critical path. Those paths are triggered when
- manually closing (`WebSocket.prototype.close`)
- receiving a close frame

You can only close a websocket once per instance, and websockets are rarely closed by nature. Not only that, `NOT_SENT` is an illogical name for a state because the closing handshake starts when sending **or** receiving a close frame.

2024-09-26 21:42 UTC, Uzlopak commented
@KhafraDev 

What if rename it to NONE?

2024-10-07 10:59 UTC, closed without merging