fix: mock interceptor should ignore trailing slashes
nodejs/undici pull request #3655
Opened 2024-09-30 22:54 UTC by Uzlopak

fixes #3649

2024-10-01 06:43 UTC, metcoder95 approved these changes

2024-10-01 20:21 UTC, Uzlopak commented
@metcoder95 

Should we wait for a second opinion/approval?

2024-10-01 22:54 UTC, KhafraDev requested changes
I don't think this is a good idea.

2024-10-02 07:46 UTC, metcoder95 commented
@KhafraDev can you elaborate on that?

2024-10-02 19:14 UTC, Uzlopak commented
@metcoder95 

I chattet with @KhafraDev and he sent me following tweet of @mcollina 

https://x.com/matteocollina/status/1828802494832705896

Seems like to every issue there is a tweet by matteo :D.

Anyhow:
I reworked on this and added ignoreTrailingSlashes as an option of MockAgent. Where do we document stuff like this?

2024-10-02 19:55 UTC, KhafraDev reviewed
Why have it as an option on the client rather than passed in the .intercept options?

2024-10-03 06:35 UTC, metcoder95 reviewed
lgtm, here we can update the docs: https://github.com/nodejs/undici/blob/main/docs/docs/api/MockPool.md#mockpoolinterceptoptions

2024-10-03 09:06 UTC, Uzlopak commented on lib/mock/mock-utils.js
> +  function resume () { }
```suggestion
  function resume () {}
```

2024-10-04 07:18 UTC, mcollina approved these changes
lgtm

2024-10-04 07:53 UTC, metcoder95 approved these changes

2024-10-04 07:53 UTC, metcoder95 commented
Shall we backport it?

2024-10-04 14:40 UTC, merged