fix: unsafe methods not causing cache purge
nodejs/undici pull request #3739
Opened 2024-10-16 06:45 UTC by flakey5

Fixes bug introduced in #3733 where unsafe methods no longer make it to the cache handler and cause a cache purge for an origin.

Also removes a duplicate test file.

cc @mcollina @Uzlopak

2024-10-16 07:18 UTC, mcollina approved these changes
lgtm

2024-10-16 07:37 UTC, Uzlopak requested changes
have to review

2024-10-16 07:47 UTC, metcoder95 commented on lib/interceptor/cache.js
> +      if (!opts.origin || (opts.method in util.safeHTTPMethods && !methods.includes(opts.method))) {
Why not `includes`?

2024-10-16 14:45 UTC, Uzlopak commented
I think there is a bigger issue here.

2024-10-16 19:19 UTC, Uzlopak commented on lib/interceptor/cache.js
> +      if (!opts.origin || (util.safeHTTPMethods.includes(opts.method) && !methods.includes(opts.method))) {
just delete this if block and your test will pass.

2024-10-16 19:20 UTC, Uzlopak commented
According to my assessment the whole logic is flawed.

2024-10-16 19:28 UTC, Uzlopak commented
provided an alternative PR #3739

2024-10-16 22:05 UTC, Uzlopak commented
What is the point of "methods" if you ignore it basically?

2024-10-16 23:25 UTC, flakey5 commented
> What is the point of "methods" if you ignore it basically?

It isn't being ignored, [the check at the beginning of each request](https://github.com/flakey5/undici/blob/ab2d8ddbe979b6142e076ddbfded86e072b4fa21/lib/interceptor/cache.js#L35) is all it's needed for

2024-10-17 09:08 UTC, Uzlopak commented
I thought about it and I think the methods option makes not much sense.

lets say you have array safeMethods with values [A,B] and methods with values [B]

So method is 

A => [A,B].includes(A) && !([B].includes(A)) => true && true => true
B => [A,B].includes(B) && !([B].includes(B)) => true && false => false
C => [A,B].includes(C) && !([B].includes(C)) => false && true => false

But what if I want to add in the future e.g. PROPFIND, which should be in theory a safe method (also ignore the fact that we would throw now a TypeError)

I add methods to PROPFIND but it wont work, because it is not in the safeMethods Array. I would purge the cache even if I added PROPFIND to the methods array.

2024-10-17 09:29 UTC, Uzlopak commented
I think you partially convinced me.

2024-10-17 09:32 UTC, Uzlopak commented on test/cache-interceptor/interceptor.js
> -'use strict'
Why did you delete this test file?

2024-10-17 09:54 UTC, Uzlopak commented
We could safe the two includes by generating ONE array

const safeMethodsToNotCache = util.safeHTTPMethods.filter(method => methods.includes(method) === false)

safeMethods would be [A,B], methods would be [B], so the resulting safeMethodToNotCache would be [A]

then the table would look like:

A => [A].includes(A) => true
B => [A].includes(B) => false
C => [A].includes(C) => false

2024-10-17 15:42 UTC, Ethan-Arrowood approved these changes
not sure why the `cache-interceptor/interceptor.js` was deleted. I'd prefer slightly more test coverage, but wont block on that. lgtm otherwise

2024-10-17 15:42 UTC, Ethan-Arrowood commented on test/interceptors/cache.js
> +    })
For coverage purposes, I'd like to see this repeated for all of the unsafe methods

2024-10-17 16:45 UTC, flakey5 commented
@Uzlopak @Ethan-Arrowood the deleted test file was a duplicate - it still exists under `test/interceptors/cache.js`

2024-10-18 08:38 UTC, Uzlopak commented
please adapt the code regarding the one array includes check.

2024-10-18 23:40 UTC, flakey5 commented
> But what if I want to add in the future e.g. PROPFIND

I do think something like the `safeMethods` option you were talking about would be valuable for this, but I'm not sure how well that behavior falls into the scope of this pr. This pr (and the original caching pr) was mainly targeting the methods specified as safe in the http semantics spec ([9.2.1](https://www.rfc-editor.org/rfc/rfc9110#section-9.2.1-3))

I do think it'd be a good idea to make an issue or pr to talk about supporting methods that were defined in extension specs though

2024-10-19 00:27 UTC, Uzlopak approved these changes
LGTM

2024-10-19 00:28 UTC, merged