lib: add `nowAbsolute` to fast timers
nodejs/undici pull request #3749
Opened 2024-10-19 02:05 UTC by flakey5

This adds a `nowAbsolute` function to the fast timers lib that allows for fetching the approximate absolute timestamp. This is useful in places like the cache interceptor and cache stores, where we're currently calling `Date.now()`.

![image](https://github.com/user-attachments/assets/ceeccd66-f276-4af0-b556-668bf30b3a37)

cc @mcollina

2024-10-19 02:05 UTC, flakey5 commented on test/utils/timers.js
> +const { test, describe } = require('node:test')
are there no tests for the fast timers api already?

2024-10-19 02:18 UTC, KhafraDev commented on test/utils/timers.js
> +    equal(Date.now(), nowAbsolute())
this looks like it'll be extremely flaky

2024-10-19 07:17 UTC, ronag requested changes
This can't use the no stall timer.

2024-10-19 07:18 UTC, ronag commented
Add another variable called fastNowAbsolute which is updated to date.now in every refresh

2024-10-23 19:39 UTC, ronag commented on lib/util/timers.js
> +let fastNowAbsolute = 0
```suggestion
let fastNowAbsolute = Date.now()
```

2024-10-23 20:41 UTC, Uzlopak commented on benchmarks/timers/now-absolute.mjs
> +import { bench, group, run } from 'mitata'
kind of trivial benchmark.

2024-11-03 15:05 UTC, mcollina commented
CI is very red

2024-11-11 21:34 UTC, mcollina commented
Still very red

2024-11-18 06:35 UTC, ronag approved these changes

2024-11-18 10:38 UTC, mcollina commented
This now conflicts

2024-11-18 17:42 UTC, merged