feat!: change default dump maxSize to infinity
nodejs/undici pull request #3788
Opened 2024-10-30 20:27 UTC by styfle

## This relates to...

- https://github.com/nodejs/undici/pull/3743#discussion_r1804929992

## Rationale

I think `dump()` should be able to dump the entire response body, not limited to a max size, you often don't know how big the response body will be.

## Changes

Change default maxSize from `1048576` (1024 * 1024) to `null` (Infinity)

### Features

N/A

### Bug Fixes

N/A

### Breaking Changes and Deprecations

Change default maxSize from `1048576` (1024 * 1024) to `null` (Infinity)

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [x] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-10-30 20:51 UTC, ronag requested changes
If the response is too big it can cause significant delay before the response is dumped. IMHO it's better to just close the connection in those cases.

2024-10-30 20:55 UTC, styfle commented
@ronag Feel free to make any changes to this PR. 

I created this PR since there was no discussion happening on the original docs PR and a DM to @mcollina suggested creating a PR to change the value to infinity.

2024-10-31 08:39 UTC, mcollina commented
> If the response is too big it can cause significant delay before the response is dumped. IMHO it's better to just close the connection in those cases.

I agree, but then why do we have a `.dump()` method to begin with?

Calling `.dump()` with a limit is _dangerous_, as users would still need to consume the rest of stream or risk crashing their process.

2024-10-31 08:42 UTC, ronag commented
> > If the response is too big it can cause significant delay before the response is dumped. IMHO it's better to just close the connection in those cases.
> 
> I agree, but then why do we have a `.dump()` method to begin with?

We have it so that if a user aborts a request with a small response we consume it and re-use the connection rather than killing it and starting a new one for the next request.

2024-10-31 08:45 UTC, mcollina commented
Ah I misunderstood this. Then we can close this.

2024-10-31 08:45 UTC, closed without merging