fix(#3817): send servername for SNI on TLS
nodejs/undici pull request #3821
Opened 2024-11-10 23:55 UTC by metcoder95

## This relates to...

## Rationale

## Changes

### Features

### Bug Fixes

### Breaking Changes and Deprecations

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

2024-11-10 23:56 UTC, metcoder95 commented
The test should cover the problem, but if anything better, let me know

2024-11-11 05:12 UTC, ronag approved these changes

2024-11-11 09:02 UTC, DTrombett commented
This does solve the certificate error but it still doesn't correctly pass the SNI, for example the following code returns a 404:
```js
request("https://example.com", {
  dispatcher: new Agent().compose(interceptors.dns()),
}).then(res => res.text()).then(console.log);
```
Is this just a limitation of interceptors?

2024-11-11 09:07 UTC, ronag commented
>  it still doesn't correctly pass the SNI, for example the following code returns a 404:

Not sure I follow. 404 is not an SNI error?

2024-11-11 09:08 UTC, ronag commented
@metcoder95 don't we also need to update the host header?

2024-11-11 09:22 UTC, DTrombett commented
Yeah, I'm sorry, I confused the server name with host; the problem is indeed the Host header and can confirm it works fine when it is manually passed

2024-11-11 12:41 UTC, mcollina approved these changes
lgtm

2024-11-11 12:45 UTC, ronag commented
> the problem is indeed the Host header and can confirm it works fine when it is manually passed

Interesting that this PR doesn't fix that. Don't we always pass servername as host header?

2024-11-11 22:54 UTC, metcoder95 commented
> > the problem is indeed the Host header and can confirm it works fine when it is manually passed
> 
> Interesting that this PR doesn't fix that. Don't we always pass servername as host header?

Noup, I tried to assess that but we were always passing the resolved IP instead (which was set as the new origin). Maybe I overlooked that but can double check. 

Good catch on the host header, I will add it 👍

2024-11-11 23:05 UTC, metcoder95 commented
@ronag ptal

2024-11-12 05:19 UTC, ronag requested changes
You should do it regardless of https or http

2024-11-12 11:20 UTC, ronag commented on lib/interceptor/dns.js
> +            origin: newOrigin
```suggestion
          dispatchOpts = {
            ...origDispatchOpts,
            origin: newOrigin,
            headers: {
              host: origin.hostname,
              ...origDispatchOpts.headers
            }
```

2024-11-19 08:49 UTC, ronag commented
@metcoder95 ping?

2024-11-19 11:38 UTC, metcoder95 commented
Sorry, was off last week and still catching up. I'll work on this over the week

2024-11-20 09:18 UTC, ronag approved these changes

2024-11-20 09:18 UTC, merged