fix(types): Pool URL
nodejs/undici pull request #507
Opened 2021-01-04 07:53 UTC by williamluke4

2021-01-04 08:56 UTC, mcollina requested changes
Can you please add a unit test?

2021-01-11 17:23 UTC, Ethan-Arrowood approved these changes

2021-01-11 17:29 UTC, ronag approved these changes

2021-01-11 18:01 UTC, mcollina approved these changes
lgtm

2021-01-11 18:10 UTC, merged