fix: unify Pool and Client APIs
nodejs/undici pull request #544
Opened 2021-02-10 08:32 UTC by ronag

- 'connect' and 'disconnect' event should have same arguments.
- connected should be an integer

2021-02-10 08:35 UTC, ronag commented
This allows e.g. using `Agent` with `Client` instead of `Pool`. So if `connections === 1` we could fallback to `Client` and avoid the overhead of `Pool`.

2021-02-10 09:00 UTC, mcollina requested changes
This needs tests

2021-02-10 11:50 UTC, ronag commented
test added

2021-02-10 13:29 UTC, mcollina approved these changes
lgtm

2021-02-10 13:51 UTC, merged

2021-02-18 20:30 UTC, Ethan-Arrowood commented
I'm going to update my docs PR to include these changes now too