fix: omit 'path' in undici.request opts (ts)
nodejs/undici pull request #559
Opened 2021-02-21 00:40 UTC by apostolos

In `undici.request|stream|pipeline` helper functions, the opts param may not contain path.

see https://github.com/nodejs/undici#undicirequesturl-opts-promise

Without this fix you get the following Typescript error:

![image](https://user-images.githubusercontent.com/41679/108612106-f0d70980-73ed-11eb-941f-43a3ec666f47.png)

But if you pass the path parameter you get a runtime error: https://github.com/nodejs/undici/blob/master/lib/agent.js#L86-L88

2021-02-21 01:06 UTC, Ethan-Arrowood commented
Unfortunately the types are quite out of date from the v3 API. I'm okay with this change though to bring it closer - I'm fairly confident not a lot of folks are using undici in TS projects just yet

2021-02-21 10:42 UTC, mcollina approved these changes
lgtm

2021-02-21 10:43 UTC, mcollina requested changes
Could you fix the types tests?

2021-02-21 17:23 UTC, apostolos commented
@mcollina type tests updated

2021-02-21 18:55 UTC, mcollina approved these changes
lgtm

@Ethan-Arrowood could you take a look?

2021-02-23 16:17 UTC, Ethan-Arrowood approved these changes

2021-02-23 16:19 UTC, merged

2021-03-26 14:13 UTC, thornyweb commented
Hello! I've just run in to this issue in our TS project :)

I can see this code has been merged but not deployed yet, do you have a planned release date at all for this fix?

Thank you!