Client lifecycle diagram
nodejs/undici pull request #567
Opened 2021-02-25 19:20 UTC by Ethan-Arrowood

Opening as a draft to start getting some feedback. I've read through the source code, tests, and existing documentation to come up with this. It may not be correct + I feel like I want to expand the "processing" state since there is a lot that happens inside of that.

2021-02-25 19:27 UTC, ronag reviewed
It won’t disconnect until keep alive timeout.

2021-02-25 19:29 UTC, Ethan-Arrowood commented
> It won’t disconnect until keep alive timeout.

Yes good point. I'll include some more details one that

2021-02-25 19:49 UTC, ronag commented
I thinking you should have another state which is just connected.

Idle - pending - running - keep alive - closing - destroyed

2021-02-25 19:54 UTC, Ethan-Arrowood commented
> I thinking you should have another state which is just connected.
> Idle - pending - running - keep alive - closing - destroyed

From what I can tell the Client never actually sits in a "connected" state. Once `dispatch` is called the Client immediately creates that socket connection and begins processing the request; even if it does not resolve the response back to the user immediately (as in the case of the async functions)

2021-02-25 22:38 UTC, mcollina requested changes

2021-02-25 22:38 UTC, mcollina commented on docs/api-lifecycle.md
> +[![A state diagram representing an Undici Client instance](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBpZGxlXG4gICAgcHJvY2Vzc2luZyAtLT4gY2xvc2luZyA6IGNsb3NlXG4gICAgaWRs
I would prefer if the image and source to be inside the repo

2021-02-26 17:16 UTC, Ethan-Arrowood commented
[![](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBpZGxlXG4gICAgcHJvY2Vzc2luZyAtLT4gY2xvc2luZyA6IGNsb3NlXG4gICAgaWRsZSAtLT4gY2xvc2luZyA6IGNsb3NlXG4gICAgaWRsZSAtLT4gZGVzdHJveWVkIDogZGVzdHJveVxuICAgIGlkbGUgLS0-IHByb2Nlc3NpbmcgOiBjb25uZWN0XG4gICAgcHJvY2Vzc2luZyAtLT4gaWRsZSA6IGRpc2Nvbm5lY3RcbiAgICBwcm9jZXNzaW5nIC0tPiBkZXN0cm95ZWQgOiBkZXN0cm95XG4gICAgY2xvc2luZyAtLT4gZGVzdHJveWVkIDogZGVzdHJveVxuICAgIGRlc3Ryb3llZCAtLT4gWypdXG5cbiAgICBzdGF0ZSBwcm9jZXNzaW5nIHtcbiAgICAgICAgWypdIC0tPiByZXN1bWluZ1xuICAgICAgICByZXN1bWluZyAtLT4gZHJhaW5pbmcgOiBkcmFpblxuICAgICAgICBkcmFpbmluZyAtLT4gcmVzdW1pbmdcbiAgICAgICAgcmVzdW1pbmcgLS0-IHJlc3VtaW5nXG4gICAgICAgIHJlc3VtaW5nIC0tPiBbKl1cbiAgICB9IiwibWVybWFpZCI6eyJ0aGVtZSI6ImJhc2UifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBpZGxlXG4gICAgcHJvY2Vzc2luZyAtLT4gY2xvc2luZyA6IGNsb3NlXG4gICAgaWRsZSAtLT4gY2xvc2luZyA6IGNsb3NlXG4gICAgaWRsZSAtLT4gZGVzdHJveWVkIDogZGVzdHJveVxuICAgIGlkbGUgLS0-IHByb2Nlc3NpbmcgOiBjb25uZWN0XG4gICAgcHJvY2Vzc2luZyAtLT4gaWRsZSA6IGRpc2Nvbm5lY3RcbiAgICBwcm9jZXNzaW5nIC0tPiBkZXN0cm95ZWQgOiBkZXN0cm95XG4gICAgY2xvc2luZyAtLT4gZGVzdHJveWVkIDogZGVzdHJveVxuICAgIGRlc3Ryb3llZCAtLT4gWypdXG5cbiAgICBzdGF0ZSBwcm9jZXNzaW5nIHtcbiAgICAgICAgWypdIC0tPiByZXN1bWluZ1xuICAgICAgICByZXN1bWluZyAtLT4gZHJhaW5pbmcgOiBkcmFpblxuICAgICAgICBkcmFpbmluZyAtLT4gcmVzdW1pbmdcbiAgICAgICAgcmVzdW1pbmcgLS0-IHJlc3VtaW5nXG4gICAgICAgIHJlc3VtaW5nIC0tPiBbKl1cbiAgICB9IiwibWVybWFpZCI6eyJ0aGVtZSI6ImJhc2UifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

@ronag what do you think about this breakdown of the **processing** state?

2021-02-26 17:36 UTC, ronag commented
@Ethan-Arrowood maybe we could have a voice call? How does your day look today?

2021-02-26 17:43 UTC, Ethan-Arrowood commented
Im free for the next couple hours! Send me an invite for whenever: ethan.arrowood@microsoft.com

2021-02-27 09:46 UTC, ronag commented
We had a call and discussed the life cycle and also other ways to make the code easier to understand.

2021-03-01 19:05 UTC, Ethan-Arrowood commented
@ronag when a Client is "connected" (the socket connection has been established), can requests be queued without being processed? Or is the action of dispatching a request to a client always going to immediately kick off the processing/running actions?

2021-03-01 19:52 UTC, Ethan-Arrowood commented
Updated the diagram based on our conversation @ronag - I'm working on the detailed state descriptions now so its better understood as well

2021-03-04 08:07 UTC, mcollina requested changes
In the `processing` sub-diagram, you need a keep-alive state that goes back to the beginning or times out.

2021-03-04 15:44 UTC, Ethan-Arrowood commented
> In the processing sub-diagram, you need a keep-alive state that goes back to the beginning or times out.

IMO this is what the `pending` state represents, connected but not processing requests. The `keepAlive` event is what transitions the `Client` from `processing` back to `pending`. And when that socket connection timesout, the `timeOut` event transitions from `pending` to `init`.

2021-03-04 22:44 UTC, mcollina commented
I got confused by having both done and keep alive ending in the same dot.

2021-03-04 22:44 UTC, mcollina approved these changes
lgtm

2021-03-08 09:08 UTC, antsmartian commented on docs/api-lifecycle.md
> +  * The *connect* event transitions the `Client` to the **pending** state where requests can be queued prior to processing
`can be queued prior to processing` should be `can be queued prior to processing.` (full stop is missing)

2021-03-10 16:40 UTC, mcollina approved these changes
still lgtm

2021-03-10 16:42 UTC, Ethan-Arrowood commented
Okay _now_ i think this is good to go. I messed things up with docsify links in the initial site build. But this should clean up everything

2021-03-10 17:16 UTC, merged