added closed and destroyed properties on agent
nodejs/undici pull request #634
Opened 2021-03-28 09:17 UTC by yashshah1

(Tries to) fix #607.

Please let me know if I've missed something

2021-03-28 09:27 UTC, ronag commented
Missing tests. Please also take a look how it's implement in `Pool`.

2021-04-01 10:44 UTC, ronag commented on lib/agent/index.js
> +} = require("../core/symbols")
Unrelated change. You can just put the symbols in this file like the rest.

2021-04-01 10:45 UTC, ronag commented on lib/agent/index.js
> +        this[kClosed] = true
This should be set directly, please see how it's done in `Pool` and `Client`.

2021-04-01 10:45 UTC, ronag commented on lib/agent/index.js
> +        this[kDestroyed] = true
This should be set directly, please see how it's done in `Pool` and `Client`. Also should set `this[kClosed]`.

2021-04-01 10:45 UTC, ronag requested changes
Please fix comments and conflicts.

2021-04-03 22:16 UTC, ronag commented
ping @yashshah1

2021-04-04 06:31 UTC, yashshah1 commented
Hi, sorry was busy with a little work and a few family things, pushing all my changes today. Thank you for your patience

2021-04-04 10:18 UTC, yashshah1 commented
The file `lib/agent.js` already has implementations for `closed` and `destroyed` which were added in 9c04cfa34999. It was missing a getter for both, which I've added. Am I missing something?

2021-04-05 19:20 UTC, mcollina commented
CI is failing and it's missing tests

2021-04-07 08:10 UTC, ronag commented
I'll add tests later.

2021-04-07 08:10 UTC, merged