fix: named event args
nodejs/undici pull request #676
Opened 2021-04-03 20:23 UTC by ronag

Use named arguments (object) for events.

2021-04-03 22:31 UTC, ronag commented on docs/api/Dispatcher.md
> +  * **error** `Error`
```suggestion
  * **err** `Error`
```

2021-04-03 23:13 UTC, mcollina requested changes
I do not understand this change. Multiple event arguments are customary in Node.js

2021-04-04 10:35 UTC, ronag commented
> I do not understand this change. Multiple event arguments are customary in Node.js

I got tired trying to figure out what order would make most sense and think it's nice if users don't need to remember the order.

Don't care that much just thought this would be nice. Close?

2021-04-05 09:31 UTC, mcollina commented
I would recommend closing.

2021-04-05 11:05 UTC, closed without merging