Fix issue with util.queueMicrotask and cjs loader
nodejs/undici pull request #762
Opened 2021-04-21 19:08 UTC by pgherveou

👋 all. Thanks for this fantastic lib.
When I require undici inside Electron
and run this code

require('undici/lib/core/util.js').queueMicrotask(() => console.log('hello'))
I get a Uncaught TypeError: Illegal invocation
Looks like this is related to how the code is loaded via the cjs/loader

2021-04-21 19:15 UTC, ronag approved these changes

2021-04-21 19:23 UTC, ronag requested changes
Please fix CI and a test would be great if possible.

2021-04-21 20:29 UTC, ronag approved these changes
LGTM, a test would still be nice

2021-04-21 20:31 UTC, mcollina approved these changes
lgtm

2021-04-21 20:43 UTC, merged

2021-04-21 23:49 UTC, pgherveou commented
@ronag not really sure how we can test it since the bug only occurs when the module is required in electron. 🤔

2021-04-22 00:13 UTC, ronag commented
> @ronag not really sure how we can test it since the bug only occurs when the module is required in electron. 🤔

Is there a headless electron we can run in the CI?