fix(request): add check for kAbort type to be a function
nodejs/undici pull request #827
Opened 2021-06-09 14:17 UTC by GO3LIN

when running mocked objects in unit tests kAbort is not set to a function, fixes https://github.com/nodejs/undici/issues/824

2021-06-09 15:36 UTC, mcollina requested changes
Could you add a unit test?

2021-06-10 09:48 UTC, GO3LIN commented
@mcollina I am trying to figure out what can be a good test scenario for that fix, maybe testing the callback is still called even if the kAbort is not a function ?

2021-06-10 10:06 UTC, mcollina commented
> @mcollina I am trying to figure out what can be a good test scenario for that fix, maybe testing the callback is still called even if the kAbort is not a function ? there may be the other side scenario too, if the kAbort is a function then it's called when the response gets destroyed.

I would start adding a test from your crash.

2021-06-14 11:38 UTC, GO3LIN commented
@mcollina I am unable to reproduce the bug in the undici environment, I tried with JavaScript and TypeScript, I can't get that error. Maybe the dependencies versions are not the same.. Here's the test I wrote:

```typescript
import { MockAgent, setGlobalDispatcher, request } from '../..';


describe("index.ts test", () => {
    let mockAgent: MockAgent;
    const origin = 'https://example.com'

    beforeEach(() => {
        mockAgent = new MockAgent({ connections: 1 });
        setGlobalDispatcher(mockAgent);
    });

    it("Returns the Working parameter in a APIResponse type", async () => {
        
        // Given
        const expectedResponse = JSON.stringify({Working: 1})
        mockAgent.get(origin).intercept({
            path: '/tdd/everything',
            method: 'GET'
        }).reply(200, expectedResponse)
        
        // When
        const { statusCode, headers, trailers, body } = await request(`${origin}/tdd/everything`, {
            method: 'GET'
          })

        let response = undefined

        for await (const data of body) {
            response = data
        }

        // Then
        expect(response.toString()).toBe(expectedResponse.toString())
    });


})
```

2021-06-16 07:12 UTC, ronag requested changes
abort should be a function, I think the problem lies somewhere else

2021-06-19 22:09 UTC, jaceppo approved these changes

2021-06-29 17:54 UTC, ronag commented
This should not be possible and coverage is already at 100 without this. Thanks for trying. Closing.

2021-06-29 17:54 UTC, closed without merging