Revert "Types: changes origin to be optional on Client and Pool"
nodejs/undici pull request #903
Opened 2021-07-25 09:36 UTC by ronag

Reverts nodejs/undici#901

2021-07-25 09:36 UTC, ronag commented
I've changed my mind. This makes things weird it's better if origin is required (even if we currently don't enforce it in runtime, should probably fix that at some point) to keep the API clean.

2021-07-26 06:19 UTC, delvedor reviewed
Why? Given that you are already passing the origin to the Pool constructor it feels repetitive to pass it again here.

2021-07-26 07:22 UTC, ronag commented
> Why? Given that you are already passing the origin to the Pool constructor it feels repetitive to pass it again here.

Because it makes the API sensible. Right now it becomes just so much more complicated. It's only for `dispatch` which is not intended to be an ergonomic API anyway.

2021-07-26 07:22 UTC, ronag commented on types/client.d.ts
> -  request(options: Client.ClientRequestOptions, callback: (err: Error | null, data: Dispatcher.ResponseData) => void): void;
@delvedor: There is no such thing as `request` here.

2021-07-26 07:52 UTC, mcollina approved these changes
lgtm

2021-07-26 08:17 UTC, delvedor commented
@ronag not sure what you mean.

Furthermore, I would highly discourage to have the types not to reflect the js API. The types should be changed with the js code, otherwise it's very easy to diverge and have weird types.

2021-07-26 08:19 UTC, mcollina requested changes
I agree with @delvedor, types should map the JS api as close as possible, and `origin` is not needed there.

2021-07-26 08:40 UTC, ronag commented
I would personally add the runtime check back then. I'm quite keen on keeping the API clean and simple.

2021-07-26 09:57 UTC, delvedor commented
I still think that if you can configure the origin in the Pool constructor, requiring the user to input **again** the origin in the `pool.request` does not simplify the API, on the contrary, it makes it more obscure. It causes me to think "Why I'm configuring this twice?" or "Can I put two different origins?".

2021-07-26 10:48 UTC, ronag commented
> I still think that if you can configure the origin in the Pool constructor, requiring the user to input **again** the origin in the `pool.request` does not simplify the API, on the contrary, it makes it more obscure. It causes me to think "Why I'm configuring this twice?" or "Can I put two different origins?".

So the idea is that we have the `Dispatcher.dispatch` interface. This is the only thing that you need to implement and contains everything you need to implement. You don't need to know about anything else. If we move out `origin` is becomes an implementation detail that you must consider on a case by case basis.

This is all theoretical. If no one else is on the page then I guess we just close this.

2021-07-26 10:49 UTC, ronag commented
To make my point the current type defs are still incorrect. You need to add them for pipeline, stream and any other high level API.

2021-07-27 08:20 UTC, mcollina commented
`Client` and `Pool` should require an `origin` in their constructor only. They are in essence origin-specific, while the `Agent` is not. If an `origin` is specified it should equal to the one passed to the constructor. I'm -1 in making this a runtime requirement for `Client` or `Pool`.

I agree the types should be changed significantly as they do not allow enough flexibility. However I think we are better off without this revert until that piece is done.

2021-07-27 08:23 UTC, ronag commented
>  If an origin is specified it should equal to the one passed to the constructor. 

Agreed.

> I'm -1 in making this a runtime requirement for Client or Pool.

Agreed here as well.

I'm only arguing that it should be required per docs and type defs to keep complexity of those down.

2021-07-27 08:25 UTC, ronag commented
Anyway feel free to close.

2021-07-27 13:16 UTC, szmarczak commented
> I'm only arguing that it should be required per docs and type defs to keep complexity of those down. Trying to add this "loose" mode there will just make things difficult with little gain IMO.

TypeScript is known to be difficult to be hard at times. Valid usage > messy types

2021-07-27 13:55 UTC, szmarczak commented
> If an origin is specified it should equal to the one passed to the constructor.

Client should also accept different origins because of https://github.com/nodejs/undici/issues/644

2021-07-27 14:10 UTC, ronag commented
Wouldn’t that mean that origin is a valid but optional type? Can’t we just make it optional in the dispatch api?

2021-07-30 09:35 UTC, ronag commented
@delvedor @mcollina PTAL https://github.com/nodejs/undici/pull/903/commits/bc14292d8475d79b2a41daca52d55b6d3ad80228 which I think I prefer.

2021-07-30 14:13 UTC, delvedor approved these changes
LGTM

2021-07-31 15:09 UTC, merged